/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.OutputFormatType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * Features supported by the model.
 */
@JsonPropertyOrder({
  CustomModelFeatures.JSON_PROPERTY_SUPPORTS_TRANSCRIPTIONS,
  CustomModelFeatures.JSON_PROPERTY_SUPPORTS_ENDPOINTS,
  CustomModelFeatures.JSON_PROPERTY_SUPPORTS_TRANSCRIPTIONS_ON_SPEECH_CONTAINERS,
  CustomModelFeatures.JSON_PROPERTY_SUPPORTED_OUTPUT_FORMATS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T10:07:46.057250+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class CustomModelFeatures {
  public static final String JSON_PROPERTY_SUPPORTS_TRANSCRIPTIONS = "supportsTranscriptions";
  @javax.annotation.Nullable
  private Boolean supportsTranscriptions;

  public static final String JSON_PROPERTY_SUPPORTS_ENDPOINTS = "supportsEndpoints";
  @javax.annotation.Nullable
  private Boolean supportsEndpoints;

  public static final String JSON_PROPERTY_SUPPORTS_TRANSCRIPTIONS_ON_SPEECH_CONTAINERS = "supportsTranscriptionsOnSpeechContainers";
  @javax.annotation.Nullable
  private Boolean supportsTranscriptionsOnSpeechContainers;

  public static final String JSON_PROPERTY_SUPPORTED_OUTPUT_FORMATS = "supportedOutputFormats";
  @javax.annotation.Nullable
  private List<OutputFormatType> supportedOutputFormats = new ArrayList<>();

  public CustomModelFeatures() { 
  }

  @JsonCreator
  public CustomModelFeatures(
    @JsonProperty(JSON_PROPERTY_SUPPORTS_TRANSCRIPTIONS) Boolean supportsTranscriptions, 
    @JsonProperty(JSON_PROPERTY_SUPPORTS_ENDPOINTS) Boolean supportsEndpoints, 
    @JsonProperty(JSON_PROPERTY_SUPPORTS_TRANSCRIPTIONS_ON_SPEECH_CONTAINERS) Boolean supportsTranscriptionsOnSpeechContainers, 
    @JsonProperty(JSON_PROPERTY_SUPPORTED_OUTPUT_FORMATS) List<OutputFormatType> supportedOutputFormats
  ) {
  this();
    this.supportsTranscriptions = supportsTranscriptions;
    this.supportsEndpoints = supportsEndpoints;
    this.supportsTranscriptionsOnSpeechContainers = supportsTranscriptionsOnSpeechContainers;
    this.supportedOutputFormats = supportedOutputFormats;
  }

  /**
   * A value indicating whether batch transcription is supported.
   * @return supportsTranscriptions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPORTS_TRANSCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSupportsTranscriptions() {
    return supportsTranscriptions;
  }




  /**
   * A value indicating whether creation of endpoints for live transcription is supported.
   * @return supportsEndpoints
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPORTS_ENDPOINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSupportsEndpoints() {
    return supportsEndpoints;
  }




  /**
   * A value indicating whether this model can be used for transcription on speech container. This feature can be added on existing models when it becomes usable on speech container.
   * @return supportsTranscriptionsOnSpeechContainers
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPORTS_TRANSCRIPTIONS_ON_SPEECH_CONTAINERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSupportsTranscriptionsOnSpeechContainers() {
    return supportsTranscriptionsOnSpeechContainers;
  }




  /**
   * Supported output formats.
   * @return supportedOutputFormats
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPORTED_OUTPUT_FORMATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<OutputFormatType> getSupportedOutputFormats() {
    return supportedOutputFormats;
  }




  /**
   * Return true if this CustomModelFeatures object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomModelFeatures customModelFeatures = (CustomModelFeatures) o;
    return Objects.equals(this.supportsTranscriptions, customModelFeatures.supportsTranscriptions) &&
        Objects.equals(this.supportsEndpoints, customModelFeatures.supportsEndpoints) &&
        Objects.equals(this.supportsTranscriptionsOnSpeechContainers, customModelFeatures.supportsTranscriptionsOnSpeechContainers) &&
        Objects.equals(this.supportedOutputFormats, customModelFeatures.supportedOutputFormats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supportsTranscriptions, supportsEndpoints, supportsTranscriptionsOnSpeechContainers, supportedOutputFormats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomModelFeatures {\n");
    sb.append("    supportsTranscriptions: ").append(toIndentedString(supportsTranscriptions)).append("\n");
    sb.append("    supportsEndpoints: ").append(toIndentedString(supportsEndpoints)).append("\n");
    sb.append("    supportsTranscriptionsOnSpeechContainers: ").append(toIndentedString(supportsTranscriptionsOnSpeechContainers)).append("\n");
    sb.append("    supportedOutputFormats: ").append(toIndentedString(supportedOutputFormats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `supportsTranscriptions` to the URL query string
    if (getSupportsTranscriptions() != null) {
      joiner.add(String.format("%ssupportsTranscriptions%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSupportsTranscriptions()))));
    }

    // add `supportsEndpoints` to the URL query string
    if (getSupportsEndpoints() != null) {
      joiner.add(String.format("%ssupportsEndpoints%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSupportsEndpoints()))));
    }

    // add `supportsTranscriptionsOnSpeechContainers` to the URL query string
    if (getSupportsTranscriptionsOnSpeechContainers() != null) {
      joiner.add(String.format("%ssupportsTranscriptionsOnSpeechContainers%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSupportsTranscriptionsOnSpeechContainers()))));
    }

    // add `supportedOutputFormats` to the URL query string
    if (getSupportedOutputFormats() != null) {
      for (int i = 0; i < getSupportedOutputFormats().size(); i++) {
        if (getSupportedOutputFormats().get(i) != null) {
          joiner.add(String.format("%ssupportedOutputFormats%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              ApiClient.urlEncode(ApiClient.valueToString(getSupportedOutputFormats().get(i)))));
        }
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private CustomModelFeatures instance;

    public Builder() {
      this(new CustomModelFeatures());
    }

    protected Builder(CustomModelFeatures instance) {
      this.instance = instance;
    }

    public CustomModelFeatures.Builder supportsTranscriptions(Boolean supportsTranscriptions) {
      this.instance.supportsTranscriptions = supportsTranscriptions;
      return this;
    }
    public CustomModelFeatures.Builder supportsEndpoints(Boolean supportsEndpoints) {
      this.instance.supportsEndpoints = supportsEndpoints;
      return this;
    }
    public CustomModelFeatures.Builder supportsTranscriptionsOnSpeechContainers(Boolean supportsTranscriptionsOnSpeechContainers) {
      this.instance.supportsTranscriptionsOnSpeechContainers = supportsTranscriptionsOnSpeechContainers;
      return this;
    }
    public CustomModelFeatures.Builder supportedOutputFormats(List<OutputFormatType> supportedOutputFormats) {
      this.instance.supportedOutputFormats = supportedOutputFormats;
      return this;
    }


    /**
    * returns a built CustomModelFeatures instance.
    *
    * The builder is not reusable.
    */
    public CustomModelFeatures build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static CustomModelFeatures.Builder builder() {
    return new CustomModelFeatures.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public CustomModelFeatures.Builder toBuilder() {
    return new CustomModelFeatures.Builder()
      .supportsTranscriptions(getSupportsTranscriptions())
      .supportsEndpoints(getSupportsEndpoints())
      .supportsTranscriptionsOnSpeechContainers(getSupportsTranscriptionsOnSpeechContainers())
      .supportedOutputFormats(getSupportedOutputFormats());
  }

}

