/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.CustomModelLinks;
import org.openapitools.client.model.CustomModelProperties;
import org.openapitools.client.model.EntityReference;
import org.openapitools.client.model.Status;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * CustomModel
 */
@JsonPropertyOrder({
  CustomModel.JSON_PROPERTY_LINKS,
  CustomModel.JSON_PROPERTY_PROPERTIES,
  CustomModel.JSON_PROPERTY_PROJECT,
  CustomModel.JSON_PROPERTY_TEXT,
  CustomModel.JSON_PROPERTY_BASE_MODEL,
  CustomModel.JSON_PROPERTY_DATASETS,
  CustomModel.JSON_PROPERTY_CUSTOM_PROPERTIES,
  CustomModel.JSON_PROPERTY_SELF,
  CustomModel.JSON_PROPERTY_LOCALE,
  CustomModel.JSON_PROPERTY_DISPLAY_NAME,
  CustomModel.JSON_PROPERTY_DESCRIPTION,
  CustomModel.JSON_PROPERTY_LAST_ACTION_DATE_TIME,
  CustomModel.JSON_PROPERTY_STATUS,
  CustomModel.JSON_PROPERTY_CREATED_DATE_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T10:07:46.057250+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class CustomModel {
  public static final String JSON_PROPERTY_LINKS = "links";
  @javax.annotation.Nullable
  private CustomModelLinks links;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @javax.annotation.Nullable
  private CustomModelProperties properties;

  public static final String JSON_PROPERTY_PROJECT = "project";
  @javax.annotation.Nullable
  private EntityReference project;

  public static final String JSON_PROPERTY_TEXT = "text";
  @javax.annotation.Nullable
  private String text;

  public static final String JSON_PROPERTY_BASE_MODEL = "baseModel";
  @javax.annotation.Nullable
  private EntityReference baseModel;

  public static final String JSON_PROPERTY_DATASETS = "datasets";
  @javax.annotation.Nullable
  private List<EntityReference> datasets = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_PROPERTIES = "customProperties";
  @javax.annotation.Nullable
  private Map<String, String> customProperties = new HashMap<>();

  public static final String JSON_PROPERTY_SELF = "self";
  @javax.annotation.Nullable
  private URI self;

  public static final String JSON_PROPERTY_LOCALE = "locale";
  @javax.annotation.Nonnull
  private String locale;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @javax.annotation.Nonnull
  private String displayName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_LAST_ACTION_DATE_TIME = "lastActionDateTime";
  @javax.annotation.Nullable
  private OffsetDateTime lastActionDateTime;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private Status status;

  public static final String JSON_PROPERTY_CREATED_DATE_TIME = "createdDateTime";
  @javax.annotation.Nullable
  private OffsetDateTime createdDateTime;

  public CustomModel() { 
  }

  @JsonCreator
  public CustomModel(
    @JsonProperty(JSON_PROPERTY_SELF) URI self, 
    @JsonProperty(JSON_PROPERTY_LAST_ACTION_DATE_TIME) OffsetDateTime lastActionDateTime, 
    @JsonProperty(JSON_PROPERTY_CREATED_DATE_TIME) OffsetDateTime createdDateTime
  ) {
  this();
    this.self = self;
    this.lastActionDateTime = lastActionDateTime;
    this.createdDateTime = createdDateTime;
  }

  public CustomModel links(@javax.annotation.Nullable CustomModelLinks links) {
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CustomModelLinks getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@javax.annotation.Nullable CustomModelLinks links) {
    this.links = links;
  }


  public CustomModel properties(@javax.annotation.Nullable CustomModelProperties properties) {
    this.properties = properties;
    return this;
  }

  /**
   * Get properties
   * @return properties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CustomModelProperties getProperties() {
    return properties;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperties(@javax.annotation.Nullable CustomModelProperties properties) {
    this.properties = properties;
  }


  public CustomModel project(@javax.annotation.Nullable EntityReference project) {
    this.project = project;
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EntityReference getProject() {
    return project;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProject(@javax.annotation.Nullable EntityReference project) {
    this.project = project;
  }


  public CustomModel text(@javax.annotation.Nullable String text) {
    this.text = text;
    return this;
  }

  /**
   * The text used to adapt this language model.
   * @return text
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }


  public CustomModel baseModel(@javax.annotation.Nullable EntityReference baseModel) {
    this.baseModel = baseModel;
    return this;
  }

  /**
   * Get baseModel
   * @return baseModel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BASE_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EntityReference getBaseModel() {
    return baseModel;
  }


  @JsonProperty(JSON_PROPERTY_BASE_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBaseModel(@javax.annotation.Nullable EntityReference baseModel) {
    this.baseModel = baseModel;
  }


  public CustomModel datasets(@javax.annotation.Nullable List<EntityReference> datasets) {
    this.datasets = datasets;
    return this;
  }

  public CustomModel addDatasetsItem(EntityReference datasetsItem) {
    if (this.datasets == null) {
      this.datasets = new ArrayList<>();
    }
    this.datasets.add(datasetsItem);
    return this;
  }

  /**
   * Datasets used for adaptation.
   * @return datasets
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATASETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<EntityReference> getDatasets() {
    return datasets;
  }


  @JsonProperty(JSON_PROPERTY_DATASETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatasets(@javax.annotation.Nullable List<EntityReference> datasets) {
    this.datasets = datasets;
  }


  public CustomModel customProperties(@javax.annotation.Nullable Map<String, String> customProperties) {
    this.customProperties = customProperties;
    return this;
  }

  public CustomModel putCustomPropertiesItem(String key, String customPropertiesItem) {
    if (this.customProperties == null) {
      this.customProperties = new HashMap<>();
    }
    this.customProperties.put(key, customPropertiesItem);
    return this;
  }

  /**
   * The custom properties of this entity. The maximum allowed key length is 64 characters, the maximum  allowed value length is 256 characters and the count of allowed entries is 10.
   * @return customProperties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getCustomProperties() {
    return customProperties;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomProperties(@javax.annotation.Nullable Map<String, String> customProperties) {
    this.customProperties = customProperties;
  }


  /**
   * The location of this entity.
   * @return self
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getSelf() {
    return self;
  }




  public CustomModel locale(@javax.annotation.Nonnull String locale) {
    this.locale = locale;
    return this;
  }

  /**
   * The locale of the contained data.
   * @return locale
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLocale() {
    return locale;
  }


  @JsonProperty(JSON_PROPERTY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocale(@javax.annotation.Nonnull String locale) {
    this.locale = locale;
  }


  public CustomModel displayName(@javax.annotation.Nonnull String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * The display name of the object.
   * @return displayName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayName(@javax.annotation.Nonnull String displayName) {
    this.displayName = displayName;
  }


  public CustomModel description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * The description of the object.
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  /**
   * The time-stamp when the current status was entered.  The time stamp is encoded as ISO 8601 date and time format  (\&quot;YYYY-MM-DDThh:mm:ssZ\&quot;, see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).
   * @return lastActionDateTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_ACTION_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getLastActionDateTime() {
    return lastActionDateTime;
  }




  public CustomModel status(@javax.annotation.Nullable Status status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Status getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable Status status) {
    this.status = status;
  }


  /**
   * The time-stamp when the object was created.  The time stamp is encoded as ISO 8601 date and time format  (\&quot;YYYY-MM-DDThh:mm:ssZ\&quot;, see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).
   * @return createdDateTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }




  /**
   * Return true if this CustomModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomModel customModel = (CustomModel) o;
    return Objects.equals(this.links, customModel.links) &&
        Objects.equals(this.properties, customModel.properties) &&
        Objects.equals(this.project, customModel.project) &&
        Objects.equals(this.text, customModel.text) &&
        Objects.equals(this.baseModel, customModel.baseModel) &&
        Objects.equals(this.datasets, customModel.datasets) &&
        Objects.equals(this.customProperties, customModel.customProperties) &&
        Objects.equals(this.self, customModel.self) &&
        Objects.equals(this.locale, customModel.locale) &&
        Objects.equals(this.displayName, customModel.displayName) &&
        Objects.equals(this.description, customModel.description) &&
        Objects.equals(this.lastActionDateTime, customModel.lastActionDateTime) &&
        Objects.equals(this.status, customModel.status) &&
        Objects.equals(this.createdDateTime, customModel.createdDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, properties, project, text, baseModel, datasets, customProperties, self, locale, displayName, description, lastActionDateTime, status, createdDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomModel {\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    baseModel: ").append(toIndentedString(baseModel)).append("\n");
    sb.append("    datasets: ").append(toIndentedString(datasets)).append("\n");
    sb.append("    customProperties: ").append(toIndentedString(customProperties)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    lastActionDateTime: ").append(toIndentedString(lastActionDateTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `self` to the URL query string
    if (getSelf() != null) {
      joiner.add(String.format("%sself%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSelf()))));
    }

    // add `locale` to the URL query string
    if (getLocale() != null) {
      joiner.add(String.format("%slocale%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLocale()))));
    }

    // add `displayName` to the URL query string
    if (getDisplayName() != null) {
      joiner.add(String.format("%sdisplayName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisplayName()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `lastActionDateTime` to the URL query string
    if (getLastActionDateTime() != null) {
      joiner.add(String.format("%slastActionDateTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastActionDateTime()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `createdDateTime` to the URL query string
    if (getCreatedDateTime() != null) {
      joiner.add(String.format("%screatedDateTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedDateTime()))));
    }

    return joiner.toString();
  }

    public static class Builder {

    private CustomModel instance;

    public Builder() {
      this(new CustomModel());
    }

    protected Builder(CustomModel instance) {
      this.instance = instance;
    }

    public CustomModel.Builder links(CustomModelLinks links) {
      this.instance.links = links;
      return this;
    }
    public CustomModel.Builder properties(CustomModelProperties properties) {
      this.instance.properties = properties;
      return this;
    }
    public CustomModel.Builder project(EntityReference project) {
      this.instance.project = project;
      return this;
    }
    public CustomModel.Builder text(String text) {
      this.instance.text = text;
      return this;
    }
    public CustomModel.Builder baseModel(EntityReference baseModel) {
      this.instance.baseModel = baseModel;
      return this;
    }
    public CustomModel.Builder datasets(List<EntityReference> datasets) {
      this.instance.datasets = datasets;
      return this;
    }
    public CustomModel.Builder customProperties(Map<String, String> customProperties) {
      this.instance.customProperties = customProperties;
      return this;
    }
    public CustomModel.Builder self(URI self) {
      this.instance.self = self;
      return this;
    }
    public CustomModel.Builder locale(String locale) {
      this.instance.locale = locale;
      return this;
    }
    public CustomModel.Builder displayName(String displayName) {
      this.instance.displayName = displayName;
      return this;
    }
    public CustomModel.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public CustomModel.Builder lastActionDateTime(OffsetDateTime lastActionDateTime) {
      this.instance.lastActionDateTime = lastActionDateTime;
      return this;
    }
    public CustomModel.Builder status(Status status) {
      this.instance.status = status;
      return this;
    }
    public CustomModel.Builder createdDateTime(OffsetDateTime createdDateTime) {
      this.instance.createdDateTime = createdDateTime;
      return this;
    }


    /**
    * returns a built CustomModel instance.
    *
    * The builder is not reusable.
    */
    public CustomModel build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static CustomModel.Builder builder() {
    return new CustomModel.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public CustomModel.Builder toBuilder() {
    return new CustomModel.Builder()
      .self(getSelf())
      .locale(getLocale())
      .displayName(getDisplayName())
      .description(getDescription())
      .lastActionDateTime(getLastActionDateTime())
      .status(getStatus())
      .createdDateTime(getCreatedDateTime());
  }

}

