/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.CustomModelDeprecationDates;
import org.openapitools.client.model.CustomModelFeatures;
import org.openapitools.client.model.EntityError;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * CustomModelProperties
 */
@JsonPropertyOrder({
  CustomModelProperties.JSON_PROPERTY_CUSTOM_MODEL_WEIGHT_PERCENT,
  CustomModelProperties.JSON_PROPERTY_DEPRECATION_DATES,
  CustomModelProperties.JSON_PROPERTY_FEATURES,
  CustomModelProperties.JSON_PROPERTY_EMAIL,
  CustomModelProperties.JSON_PROPERTY_ERROR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T10:07:46.057250+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class CustomModelProperties {
  public static final String JSON_PROPERTY_CUSTOM_MODEL_WEIGHT_PERCENT = "customModelWeightPercent";
  @javax.annotation.Nullable
  private Integer customModelWeightPercent;

  public static final String JSON_PROPERTY_DEPRECATION_DATES = "deprecationDates";
  @javax.annotation.Nullable
  private CustomModelDeprecationDates deprecationDates;

  public static final String JSON_PROPERTY_FEATURES = "features";
  @javax.annotation.Nullable
  private CustomModelFeatures features;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_ERROR = "error";
  @javax.annotation.Nullable
  private EntityError error;

  public CustomModelProperties() { 
  }

  public CustomModelProperties customModelWeightPercent(@javax.annotation.Nullable Integer customModelWeightPercent) {
    this.customModelWeightPercent = customModelWeightPercent;
    return this;
  }

  /**
   * The weight of custom model between 1 (1% custom model and 99% base model) and 100 (100% custom model and 0% base model).  When this property is not set, the service chooses a suitable value (get the model to retrieve the selected weight).  Start without using this property. If needed, choose a larger (or smaller) weight to increase (or decrease) the impact of the custom model.
   * minimum: 1
   * maximum: 100
   * @return customModelWeightPercent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_MODEL_WEIGHT_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getCustomModelWeightPercent() {
    return customModelWeightPercent;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_MODEL_WEIGHT_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomModelWeightPercent(@javax.annotation.Nullable Integer customModelWeightPercent) {
    this.customModelWeightPercent = customModelWeightPercent;
  }


  public CustomModelProperties deprecationDates(@javax.annotation.Nullable CustomModelDeprecationDates deprecationDates) {
    this.deprecationDates = deprecationDates;
    return this;
  }

  /**
   * Get deprecationDates
   * @return deprecationDates
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPRECATION_DATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CustomModelDeprecationDates getDeprecationDates() {
    return deprecationDates;
  }


  @JsonProperty(JSON_PROPERTY_DEPRECATION_DATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeprecationDates(@javax.annotation.Nullable CustomModelDeprecationDates deprecationDates) {
    this.deprecationDates = deprecationDates;
  }


  public CustomModelProperties features(@javax.annotation.Nullable CustomModelFeatures features) {
    this.features = features;
    return this;
  }

  /**
   * Get features
   * @return features
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FEATURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CustomModelFeatures getFeatures() {
    return features;
  }


  @JsonProperty(JSON_PROPERTY_FEATURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeatures(@javax.annotation.Nullable CustomModelFeatures features) {
    this.features = features;
  }


  public CustomModelProperties email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * The email address to send email notifications to in case the operation completes.  The value will be removed after successfully sending the email.
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public CustomModelProperties error(@javax.annotation.Nullable EntityError error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EntityError getError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@javax.annotation.Nullable EntityError error) {
    this.error = error;
  }


  /**
   * Return true if this CustomModelProperties object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomModelProperties customModelProperties = (CustomModelProperties) o;
    return Objects.equals(this.customModelWeightPercent, customModelProperties.customModelWeightPercent) &&
        Objects.equals(this.deprecationDates, customModelProperties.deprecationDates) &&
        Objects.equals(this.features, customModelProperties.features) &&
        Objects.equals(this.email, customModelProperties.email) &&
        Objects.equals(this.error, customModelProperties.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customModelWeightPercent, deprecationDates, features, email, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomModelProperties {\n");
    sb.append("    customModelWeightPercent: ").append(toIndentedString(customModelWeightPercent)).append("\n");
    sb.append("    deprecationDates: ").append(toIndentedString(deprecationDates)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `customModelWeightPercent` to the URL query string
    if (getCustomModelWeightPercent() != null) {
      joiner.add(String.format("%scustomModelWeightPercent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomModelWeightPercent()))));
    }

    // add `deprecationDates` to the URL query string
    if (getDeprecationDates() != null) {
      joiner.add(getDeprecationDates().toUrlQueryString(prefix + "deprecationDates" + suffix));
    }

    // add `features` to the URL query string
    if (getFeatures() != null) {
      joiner.add(getFeatures().toUrlQueryString(prefix + "features" + suffix));
    }

    // add `email` to the URL query string
    if (getEmail() != null) {
      joiner.add(String.format("%semail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmail()))));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(getError().toUrlQueryString(prefix + "error" + suffix));
    }

    return joiner.toString();
  }

    public static class Builder {

    private CustomModelProperties instance;

    public Builder() {
      this(new CustomModelProperties());
    }

    protected Builder(CustomModelProperties instance) {
      this.instance = instance;
    }

    public CustomModelProperties.Builder customModelWeightPercent(Integer customModelWeightPercent) {
      this.instance.customModelWeightPercent = customModelWeightPercent;
      return this;
    }
    public CustomModelProperties.Builder deprecationDates(CustomModelDeprecationDates deprecationDates) {
      this.instance.deprecationDates = deprecationDates;
      return this;
    }
    public CustomModelProperties.Builder features(CustomModelFeatures features) {
      this.instance.features = features;
      return this;
    }
    public CustomModelProperties.Builder email(String email) {
      this.instance.email = email;
      return this;
    }
    public CustomModelProperties.Builder error(EntityError error) {
      this.instance.error = error;
      return this;
    }


    /**
    * returns a built CustomModelProperties instance.
    *
    * The builder is not reusable.
    */
    public CustomModelProperties build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static CustomModelProperties.Builder builder() {
    return new CustomModelProperties.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public CustomModelProperties.Builder toBuilder() {
    return new CustomModelProperties.Builder()
      .customModelWeightPercent(getCustomModelWeightPercent())
      .deprecationDates(getDeprecationDates())
      .features(getFeatures())
      .email(getEmail())
      .error(getError());
  }

}

