/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * EditsSummary
 */
@JsonPropertyOrder({
  EditsSummary.JSON_PROPERTY_NUMBER_OF_EDITS,
  EditsSummary.JSON_PROPERTY_PERCENTAGE_OF_ALL_EDITS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T10:07:46.057250+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class EditsSummary {
  public static final String JSON_PROPERTY_NUMBER_OF_EDITS = "numberOfEdits";
  @javax.annotation.Nullable
  private Integer numberOfEdits;

  public static final String JSON_PROPERTY_PERCENTAGE_OF_ALL_EDITS = "percentageOfAllEdits";
  @javax.annotation.Nullable
  private Double percentageOfAllEdits;

  public EditsSummary() { 
  }

  @JsonCreator
  public EditsSummary(
    @JsonProperty(JSON_PROPERTY_NUMBER_OF_EDITS) Integer numberOfEdits, 
    @JsonProperty(JSON_PROPERTY_PERCENTAGE_OF_ALL_EDITS) Double percentageOfAllEdits
  ) {
  this();
    this.numberOfEdits = numberOfEdits;
    this.percentageOfAllEdits = percentageOfAllEdits;
  }

  /**
   * The optional number of edits for a given type of error of the recognized transcription in comparison with the human transcription.
   * @return numberOfEdits
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMBER_OF_EDITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getNumberOfEdits() {
    return numberOfEdits;
  }




  /**
   * The optional percentage of edits for a given type of error of the recognized transcription in comparison with the human transcription.
   * @return percentageOfAllEdits
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERCENTAGE_OF_ALL_EDITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPercentageOfAllEdits() {
    return percentageOfAllEdits;
  }




  /**
   * Return true if this EditsSummary object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditsSummary editsSummary = (EditsSummary) o;
    return Objects.equals(this.numberOfEdits, editsSummary.numberOfEdits) &&
        Objects.equals(this.percentageOfAllEdits, editsSummary.percentageOfAllEdits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfEdits, percentageOfAllEdits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditsSummary {\n");
    sb.append("    numberOfEdits: ").append(toIndentedString(numberOfEdits)).append("\n");
    sb.append("    percentageOfAllEdits: ").append(toIndentedString(percentageOfAllEdits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `numberOfEdits` to the URL query string
    if (getNumberOfEdits() != null) {
      joiner.add(String.format("%snumberOfEdits%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNumberOfEdits()))));
    }

    // add `percentageOfAllEdits` to the URL query string
    if (getPercentageOfAllEdits() != null) {
      joiner.add(String.format("%spercentageOfAllEdits%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPercentageOfAllEdits()))));
    }

    return joiner.toString();
  }

    public static class Builder {

    private EditsSummary instance;

    public Builder() {
      this(new EditsSummary());
    }

    protected Builder(EditsSummary instance) {
      this.instance = instance;
    }

    public EditsSummary.Builder numberOfEdits(Integer numberOfEdits) {
      this.instance.numberOfEdits = numberOfEdits;
      return this;
    }
    public EditsSummary.Builder percentageOfAllEdits(Double percentageOfAllEdits) {
      this.instance.percentageOfAllEdits = percentageOfAllEdits;
      return this;
    }


    /**
    * returns a built EditsSummary instance.
    *
    * The builder is not reusable.
    */
    public EditsSummary build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static EditsSummary.Builder builder() {
    return new EditsSummary.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public EditsSummary.Builder toBuilder() {
    return new EditsSummary.Builder()
      .numberOfEdits(getNumberOfEdits())
      .percentageOfAllEdits(getPercentageOfAllEdits());
  }

}

