/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * EndpointPropertiesUpdate
 */
@JsonPropertyOrder({
  EndpointPropertiesUpdate.JSON_PROPERTY_CONTENT_LOGGING_ENABLED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T10:07:46.057250+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class EndpointPropertiesUpdate {
  public static final String JSON_PROPERTY_CONTENT_LOGGING_ENABLED = "contentLoggingEnabled";
  @javax.annotation.Nullable
  private Boolean contentLoggingEnabled;

  public EndpointPropertiesUpdate() { 
  }

  public EndpointPropertiesUpdate contentLoggingEnabled(@javax.annotation.Nullable Boolean contentLoggingEnabled) {
    this.contentLoggingEnabled = contentLoggingEnabled;
    return this;
  }

  /**
   * A value indicating whether content logging (audio &amp; transcriptions)  is being used for a deployment.
   * @return contentLoggingEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENT_LOGGING_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContentLoggingEnabled() {
    return contentLoggingEnabled;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_LOGGING_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentLoggingEnabled(@javax.annotation.Nullable Boolean contentLoggingEnabled) {
    this.contentLoggingEnabled = contentLoggingEnabled;
  }


  /**
   * Return true if this EndpointPropertiesUpdate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EndpointPropertiesUpdate endpointPropertiesUpdate = (EndpointPropertiesUpdate) o;
    return Objects.equals(this.contentLoggingEnabled, endpointPropertiesUpdate.contentLoggingEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentLoggingEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EndpointPropertiesUpdate {\n");
    sb.append("    contentLoggingEnabled: ").append(toIndentedString(contentLoggingEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `contentLoggingEnabled` to the URL query string
    if (getContentLoggingEnabled() != null) {
      joiner.add(String.format("%scontentLoggingEnabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContentLoggingEnabled()))));
    }

    return joiner.toString();
  }

    public static class Builder {

    private EndpointPropertiesUpdate instance;

    public Builder() {
      this(new EndpointPropertiesUpdate());
    }

    protected Builder(EndpointPropertiesUpdate instance) {
      this.instance = instance;
    }

    public EndpointPropertiesUpdate.Builder contentLoggingEnabled(Boolean contentLoggingEnabled) {
      this.instance.contentLoggingEnabled = contentLoggingEnabled;
      return this;
    }


    /**
    * returns a built EndpointPropertiesUpdate instance.
    *
    * The builder is not reusable.
    */
    public EndpointPropertiesUpdate build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static EndpointPropertiesUpdate.Builder builder() {
    return new EndpointPropertiesUpdate.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public EndpointPropertiesUpdate.Builder toBuilder() {
    return new EndpointPropertiesUpdate.Builder()
      .contentLoggingEnabled(getContentLoggingEnabled());
  }

}

