/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.EntityError;
import org.openapitools.client.model.TokenErrorDetails;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * EvaluationProperties
 */
@JsonPropertyOrder({
  EvaluationProperties.JSON_PROPERTY_WORD_ERROR_RATE1,
  EvaluationProperties.JSON_PROPERTY_SENTENCE_ERROR_RATE1,
  EvaluationProperties.JSON_PROPERTY_TOKEN_ERROR_RATE1,
  EvaluationProperties.JSON_PROPERTY_SENTENCE_COUNT1,
  EvaluationProperties.JSON_PROPERTY_WORD_COUNT1,
  EvaluationProperties.JSON_PROPERTY_CORRECT_WORD_COUNT1,
  EvaluationProperties.JSON_PROPERTY_WORD_SUBSTITUTION_COUNT1,
  EvaluationProperties.JSON_PROPERTY_WORD_DELETION_COUNT1,
  EvaluationProperties.JSON_PROPERTY_WORD_INSERTION_COUNT1,
  EvaluationProperties.JSON_PROPERTY_TOKEN_COUNT1,
  EvaluationProperties.JSON_PROPERTY_CORRECT_TOKEN_COUNT1,
  EvaluationProperties.JSON_PROPERTY_TOKEN_SUBSTITUTION_COUNT1,
  EvaluationProperties.JSON_PROPERTY_TOKEN_DELETION_COUNT1,
  EvaluationProperties.JSON_PROPERTY_TOKEN_INSERTION_COUNT1,
  EvaluationProperties.JSON_PROPERTY_TOKEN_ERRORS1,
  EvaluationProperties.JSON_PROPERTY_WORD_ERROR_RATE2,
  EvaluationProperties.JSON_PROPERTY_SENTENCE_ERROR_RATE2,
  EvaluationProperties.JSON_PROPERTY_TOKEN_ERROR_RATE2,
  EvaluationProperties.JSON_PROPERTY_SENTENCE_COUNT2,
  EvaluationProperties.JSON_PROPERTY_WORD_COUNT2,
  EvaluationProperties.JSON_PROPERTY_CORRECT_WORD_COUNT2,
  EvaluationProperties.JSON_PROPERTY_WORD_SUBSTITUTION_COUNT2,
  EvaluationProperties.JSON_PROPERTY_WORD_DELETION_COUNT2,
  EvaluationProperties.JSON_PROPERTY_WORD_INSERTION_COUNT2,
  EvaluationProperties.JSON_PROPERTY_TOKEN_COUNT2,
  EvaluationProperties.JSON_PROPERTY_CORRECT_TOKEN_COUNT2,
  EvaluationProperties.JSON_PROPERTY_TOKEN_SUBSTITUTION_COUNT2,
  EvaluationProperties.JSON_PROPERTY_TOKEN_DELETION_COUNT2,
  EvaluationProperties.JSON_PROPERTY_TOKEN_INSERTION_COUNT2,
  EvaluationProperties.JSON_PROPERTY_TOKEN_ERRORS2,
  EvaluationProperties.JSON_PROPERTY_EMAIL,
  EvaluationProperties.JSON_PROPERTY_ERROR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T10:07:46.057250+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class EvaluationProperties {
  public static final String JSON_PROPERTY_WORD_ERROR_RATE1 = "wordErrorRate1";
  @javax.annotation.Nullable
  private Double wordErrorRate1;

  public static final String JSON_PROPERTY_SENTENCE_ERROR_RATE1 = "sentenceErrorRate1";
  @javax.annotation.Nullable
  private Double sentenceErrorRate1;

  public static final String JSON_PROPERTY_TOKEN_ERROR_RATE1 = "tokenErrorRate1";
  @javax.annotation.Nullable
  private Double tokenErrorRate1;

  public static final String JSON_PROPERTY_SENTENCE_COUNT1 = "sentenceCount1";
  @javax.annotation.Nullable
  private Integer sentenceCount1;

  public static final String JSON_PROPERTY_WORD_COUNT1 = "wordCount1";
  @javax.annotation.Nullable
  private Integer wordCount1;

  public static final String JSON_PROPERTY_CORRECT_WORD_COUNT1 = "correctWordCount1";
  @javax.annotation.Nullable
  private Integer correctWordCount1;

  public static final String JSON_PROPERTY_WORD_SUBSTITUTION_COUNT1 = "wordSubstitutionCount1";
  @javax.annotation.Nullable
  private Integer wordSubstitutionCount1;

  public static final String JSON_PROPERTY_WORD_DELETION_COUNT1 = "wordDeletionCount1";
  @javax.annotation.Nullable
  private Integer wordDeletionCount1;

  public static final String JSON_PROPERTY_WORD_INSERTION_COUNT1 = "wordInsertionCount1";
  @javax.annotation.Nullable
  private Integer wordInsertionCount1;

  public static final String JSON_PROPERTY_TOKEN_COUNT1 = "tokenCount1";
  @javax.annotation.Nullable
  private Integer tokenCount1;

  public static final String JSON_PROPERTY_CORRECT_TOKEN_COUNT1 = "correctTokenCount1";
  @javax.annotation.Nullable
  private Integer correctTokenCount1;

  public static final String JSON_PROPERTY_TOKEN_SUBSTITUTION_COUNT1 = "tokenSubstitutionCount1";
  @javax.annotation.Nullable
  private Integer tokenSubstitutionCount1;

  public static final String JSON_PROPERTY_TOKEN_DELETION_COUNT1 = "tokenDeletionCount1";
  @javax.annotation.Nullable
  private Integer tokenDeletionCount1;

  public static final String JSON_PROPERTY_TOKEN_INSERTION_COUNT1 = "tokenInsertionCount1";
  @javax.annotation.Nullable
  private Integer tokenInsertionCount1;

  public static final String JSON_PROPERTY_TOKEN_ERRORS1 = "tokenErrors1";
  @javax.annotation.Nullable
  private TokenErrorDetails tokenErrors1;

  public static final String JSON_PROPERTY_WORD_ERROR_RATE2 = "wordErrorRate2";
  @javax.annotation.Nullable
  private Double wordErrorRate2;

  public static final String JSON_PROPERTY_SENTENCE_ERROR_RATE2 = "sentenceErrorRate2";
  @javax.annotation.Nullable
  private Double sentenceErrorRate2;

  public static final String JSON_PROPERTY_TOKEN_ERROR_RATE2 = "tokenErrorRate2";
  @javax.annotation.Nullable
  private Double tokenErrorRate2;

  public static final String JSON_PROPERTY_SENTENCE_COUNT2 = "sentenceCount2";
  @javax.annotation.Nullable
  private Integer sentenceCount2;

  public static final String JSON_PROPERTY_WORD_COUNT2 = "wordCount2";
  @javax.annotation.Nullable
  private Integer wordCount2;

  public static final String JSON_PROPERTY_CORRECT_WORD_COUNT2 = "correctWordCount2";
  @javax.annotation.Nullable
  private Integer correctWordCount2;

  public static final String JSON_PROPERTY_WORD_SUBSTITUTION_COUNT2 = "wordSubstitutionCount2";
  @javax.annotation.Nullable
  private Integer wordSubstitutionCount2;

  public static final String JSON_PROPERTY_WORD_DELETION_COUNT2 = "wordDeletionCount2";
  @javax.annotation.Nullable
  private Integer wordDeletionCount2;

  public static final String JSON_PROPERTY_WORD_INSERTION_COUNT2 = "wordInsertionCount2";
  @javax.annotation.Nullable
  private Integer wordInsertionCount2;

  public static final String JSON_PROPERTY_TOKEN_COUNT2 = "tokenCount2";
  @javax.annotation.Nullable
  private Integer tokenCount2;

  public static final String JSON_PROPERTY_CORRECT_TOKEN_COUNT2 = "correctTokenCount2";
  @javax.annotation.Nullable
  private Integer correctTokenCount2;

  public static final String JSON_PROPERTY_TOKEN_SUBSTITUTION_COUNT2 = "tokenSubstitutionCount2";
  @javax.annotation.Nullable
  private Integer tokenSubstitutionCount2;

  public static final String JSON_PROPERTY_TOKEN_DELETION_COUNT2 = "tokenDeletionCount2";
  @javax.annotation.Nullable
  private Integer tokenDeletionCount2;

  public static final String JSON_PROPERTY_TOKEN_INSERTION_COUNT2 = "tokenInsertionCount2";
  @javax.annotation.Nullable
  private Integer tokenInsertionCount2;

  public static final String JSON_PROPERTY_TOKEN_ERRORS2 = "tokenErrors2";
  @javax.annotation.Nullable
  private TokenErrorDetails tokenErrors2;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_ERROR = "error";
  @javax.annotation.Nullable
  private EntityError error;

  public EvaluationProperties() { 
  }

  @JsonCreator
  public EvaluationProperties(
    @JsonProperty(JSON_PROPERTY_WORD_ERROR_RATE1) Double wordErrorRate1, 
    @JsonProperty(JSON_PROPERTY_SENTENCE_ERROR_RATE1) Double sentenceErrorRate1, 
    @JsonProperty(JSON_PROPERTY_TOKEN_ERROR_RATE1) Double tokenErrorRate1, 
    @JsonProperty(JSON_PROPERTY_SENTENCE_COUNT1) Integer sentenceCount1, 
    @JsonProperty(JSON_PROPERTY_WORD_COUNT1) Integer wordCount1, 
    @JsonProperty(JSON_PROPERTY_CORRECT_WORD_COUNT1) Integer correctWordCount1, 
    @JsonProperty(JSON_PROPERTY_WORD_SUBSTITUTION_COUNT1) Integer wordSubstitutionCount1, 
    @JsonProperty(JSON_PROPERTY_WORD_DELETION_COUNT1) Integer wordDeletionCount1, 
    @JsonProperty(JSON_PROPERTY_WORD_INSERTION_COUNT1) Integer wordInsertionCount1, 
    @JsonProperty(JSON_PROPERTY_TOKEN_COUNT1) Integer tokenCount1, 
    @JsonProperty(JSON_PROPERTY_CORRECT_TOKEN_COUNT1) Integer correctTokenCount1, 
    @JsonProperty(JSON_PROPERTY_TOKEN_SUBSTITUTION_COUNT1) Integer tokenSubstitutionCount1, 
    @JsonProperty(JSON_PROPERTY_TOKEN_DELETION_COUNT1) Integer tokenDeletionCount1, 
    @JsonProperty(JSON_PROPERTY_TOKEN_INSERTION_COUNT1) Integer tokenInsertionCount1, 
    @JsonProperty(JSON_PROPERTY_WORD_ERROR_RATE2) Double wordErrorRate2, 
    @JsonProperty(JSON_PROPERTY_SENTENCE_ERROR_RATE2) Double sentenceErrorRate2, 
    @JsonProperty(JSON_PROPERTY_TOKEN_ERROR_RATE2) Double tokenErrorRate2, 
    @JsonProperty(JSON_PROPERTY_SENTENCE_COUNT2) Integer sentenceCount2, 
    @JsonProperty(JSON_PROPERTY_WORD_COUNT2) Integer wordCount2, 
    @JsonProperty(JSON_PROPERTY_CORRECT_WORD_COUNT2) Integer correctWordCount2, 
    @JsonProperty(JSON_PROPERTY_WORD_SUBSTITUTION_COUNT2) Integer wordSubstitutionCount2, 
    @JsonProperty(JSON_PROPERTY_WORD_DELETION_COUNT2) Integer wordDeletionCount2, 
    @JsonProperty(JSON_PROPERTY_WORD_INSERTION_COUNT2) Integer wordInsertionCount2, 
    @JsonProperty(JSON_PROPERTY_TOKEN_COUNT2) Integer tokenCount2, 
    @JsonProperty(JSON_PROPERTY_CORRECT_TOKEN_COUNT2) Integer correctTokenCount2, 
    @JsonProperty(JSON_PROPERTY_TOKEN_SUBSTITUTION_COUNT2) Integer tokenSubstitutionCount2, 
    @JsonProperty(JSON_PROPERTY_TOKEN_DELETION_COUNT2) Integer tokenDeletionCount2, 
    @JsonProperty(JSON_PROPERTY_TOKEN_INSERTION_COUNT2) Integer tokenInsertionCount2
  ) {
  this();
    this.wordErrorRate1 = wordErrorRate1;
    this.sentenceErrorRate1 = sentenceErrorRate1;
    this.tokenErrorRate1 = tokenErrorRate1;
    this.sentenceCount1 = sentenceCount1;
    this.wordCount1 = wordCount1;
    this.correctWordCount1 = correctWordCount1;
    this.wordSubstitutionCount1 = wordSubstitutionCount1;
    this.wordDeletionCount1 = wordDeletionCount1;
    this.wordInsertionCount1 = wordInsertionCount1;
    this.tokenCount1 = tokenCount1;
    this.correctTokenCount1 = correctTokenCount1;
    this.tokenSubstitutionCount1 = tokenSubstitutionCount1;
    this.tokenDeletionCount1 = tokenDeletionCount1;
    this.tokenInsertionCount1 = tokenInsertionCount1;
    this.wordErrorRate2 = wordErrorRate2;
    this.sentenceErrorRate2 = sentenceErrorRate2;
    this.tokenErrorRate2 = tokenErrorRate2;
    this.sentenceCount2 = sentenceCount2;
    this.wordCount2 = wordCount2;
    this.correctWordCount2 = correctWordCount2;
    this.wordSubstitutionCount2 = wordSubstitutionCount2;
    this.wordDeletionCount2 = wordDeletionCount2;
    this.wordInsertionCount2 = wordInsertionCount2;
    this.tokenCount2 = tokenCount2;
    this.correctTokenCount2 = correctTokenCount2;
    this.tokenSubstitutionCount2 = tokenSubstitutionCount2;
    this.tokenDeletionCount2 = tokenDeletionCount2;
    this.tokenInsertionCount2 = tokenInsertionCount2;
  }

  /**
   * The word error rate of recognition with model1.
   * @return wordErrorRate1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORD_ERROR_RATE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getWordErrorRate1() {
    return wordErrorRate1;
  }




  /**
   * The sentence error rate of recognition with model1.
   * @return sentenceErrorRate1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENTENCE_ERROR_RATE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getSentenceErrorRate1() {
    return sentenceErrorRate1;
  }




  /**
   * The optional token error rate of recognition with model1.
   * @return tokenErrorRate1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_ERROR_RATE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTokenErrorRate1() {
    return tokenErrorRate1;
  }




  /**
   * The number of processed sentences by model1.
   * @return sentenceCount1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENTENCE_COUNT1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getSentenceCount1() {
    return sentenceCount1;
  }




  /**
   * The number of processed words by model1.
   * @return wordCount1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORD_COUNT1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getWordCount1() {
    return wordCount1;
  }




  /**
   * The number of correctly recognized words by model1.
   * @return correctWordCount1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CORRECT_WORD_COUNT1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getCorrectWordCount1() {
    return correctWordCount1;
  }




  /**
   * The number of recognized words by model1, that are substitutions.
   * @return wordSubstitutionCount1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORD_SUBSTITUTION_COUNT1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getWordSubstitutionCount1() {
    return wordSubstitutionCount1;
  }




  /**
   * The number of recognized words by model1, that are deletions.
   * @return wordDeletionCount1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORD_DELETION_COUNT1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getWordDeletionCount1() {
    return wordDeletionCount1;
  }




  /**
   * The number of recognized words by model1, that are insertions.
   * @return wordInsertionCount1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORD_INSERTION_COUNT1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getWordInsertionCount1() {
    return wordInsertionCount1;
  }




  /**
   * Optional the number of processed tokens by model1.
   * @return tokenCount1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_COUNT1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTokenCount1() {
    return tokenCount1;
  }




  /**
   * The optional number of correctly recognized tokens by model1.
   * @return correctTokenCount1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CORRECT_TOKEN_COUNT1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getCorrectTokenCount1() {
    return correctTokenCount1;
  }




  /**
   * The optional number of recognized tokens by model1, that are substitutions.
   * @return tokenSubstitutionCount1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_SUBSTITUTION_COUNT1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTokenSubstitutionCount1() {
    return tokenSubstitutionCount1;
  }




  /**
   * The optional number of recognized tokens by model1, that are deletions.
   * @return tokenDeletionCount1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_DELETION_COUNT1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTokenDeletionCount1() {
    return tokenDeletionCount1;
  }




  /**
   * The optional number of recognized tokens by model1, that are insertions.
   * @return tokenInsertionCount1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_INSERTION_COUNT1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTokenInsertionCount1() {
    return tokenInsertionCount1;
  }




  public EvaluationProperties tokenErrors1(@javax.annotation.Nullable TokenErrorDetails tokenErrors1) {
    this.tokenErrors1 = tokenErrors1;
    return this;
  }

  /**
   * Get tokenErrors1
   * @return tokenErrors1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_ERRORS1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TokenErrorDetails getTokenErrors1() {
    return tokenErrors1;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_ERRORS1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenErrors1(@javax.annotation.Nullable TokenErrorDetails tokenErrors1) {
    this.tokenErrors1 = tokenErrors1;
  }


  /**
   * The word error rate of recognition with model2.
   * @return wordErrorRate2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORD_ERROR_RATE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getWordErrorRate2() {
    return wordErrorRate2;
  }




  /**
   * The sentence error rate of recognition with model2.
   * @return sentenceErrorRate2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENTENCE_ERROR_RATE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getSentenceErrorRate2() {
    return sentenceErrorRate2;
  }




  /**
   * The optional token error rate of recognition with model2.
   * @return tokenErrorRate2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_ERROR_RATE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTokenErrorRate2() {
    return tokenErrorRate2;
  }




  /**
   * The number of processed sentences by model2.
   * @return sentenceCount2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENTENCE_COUNT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getSentenceCount2() {
    return sentenceCount2;
  }




  /**
   * The number of processed words by model2.
   * @return wordCount2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORD_COUNT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getWordCount2() {
    return wordCount2;
  }




  /**
   * The number of correctly recognized words by model2.
   * @return correctWordCount2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CORRECT_WORD_COUNT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getCorrectWordCount2() {
    return correctWordCount2;
  }




  /**
   * The number of recognized words by model2, that are substitutions.
   * @return wordSubstitutionCount2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORD_SUBSTITUTION_COUNT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getWordSubstitutionCount2() {
    return wordSubstitutionCount2;
  }




  /**
   * The number of recognized words by model2, that are deletions.
   * @return wordDeletionCount2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORD_DELETION_COUNT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getWordDeletionCount2() {
    return wordDeletionCount2;
  }




  /**
   * The number of recognized words by model2, that are insertions.
   * @return wordInsertionCount2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORD_INSERTION_COUNT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getWordInsertionCount2() {
    return wordInsertionCount2;
  }




  /**
   * The optional number of processed tokens by model2.
   * @return tokenCount2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_COUNT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTokenCount2() {
    return tokenCount2;
  }




  /**
   * The optional number of correctly recognized tokens by model2.
   * @return correctTokenCount2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CORRECT_TOKEN_COUNT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getCorrectTokenCount2() {
    return correctTokenCount2;
  }




  /**
   * The optional number of recognized tokens by model2, that are substitutions.
   * @return tokenSubstitutionCount2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_SUBSTITUTION_COUNT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTokenSubstitutionCount2() {
    return tokenSubstitutionCount2;
  }




  /**
   * The optional number of recognized tokens by model2, that are deletions.
   * @return tokenDeletionCount2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_DELETION_COUNT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTokenDeletionCount2() {
    return tokenDeletionCount2;
  }




  /**
   * The optional number of recognized tokens by model2, that are insertions.
   * @return tokenInsertionCount2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_INSERTION_COUNT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTokenInsertionCount2() {
    return tokenInsertionCount2;
  }




  public EvaluationProperties tokenErrors2(@javax.annotation.Nullable TokenErrorDetails tokenErrors2) {
    this.tokenErrors2 = tokenErrors2;
    return this;
  }

  /**
   * Get tokenErrors2
   * @return tokenErrors2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_ERRORS2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TokenErrorDetails getTokenErrors2() {
    return tokenErrors2;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_ERRORS2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenErrors2(@javax.annotation.Nullable TokenErrorDetails tokenErrors2) {
    this.tokenErrors2 = tokenErrors2;
  }


  public EvaluationProperties email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * The email address to send email notifications to in case the operation completes.  The value will be removed after successfully sending the email.
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public EvaluationProperties error(@javax.annotation.Nullable EntityError error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EntityError getError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@javax.annotation.Nullable EntityError error) {
    this.error = error;
  }


  /**
   * Return true if this EvaluationProperties object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvaluationProperties evaluationProperties = (EvaluationProperties) o;
    return Objects.equals(this.wordErrorRate1, evaluationProperties.wordErrorRate1) &&
        Objects.equals(this.sentenceErrorRate1, evaluationProperties.sentenceErrorRate1) &&
        Objects.equals(this.tokenErrorRate1, evaluationProperties.tokenErrorRate1) &&
        Objects.equals(this.sentenceCount1, evaluationProperties.sentenceCount1) &&
        Objects.equals(this.wordCount1, evaluationProperties.wordCount1) &&
        Objects.equals(this.correctWordCount1, evaluationProperties.correctWordCount1) &&
        Objects.equals(this.wordSubstitutionCount1, evaluationProperties.wordSubstitutionCount1) &&
        Objects.equals(this.wordDeletionCount1, evaluationProperties.wordDeletionCount1) &&
        Objects.equals(this.wordInsertionCount1, evaluationProperties.wordInsertionCount1) &&
        Objects.equals(this.tokenCount1, evaluationProperties.tokenCount1) &&
        Objects.equals(this.correctTokenCount1, evaluationProperties.correctTokenCount1) &&
        Objects.equals(this.tokenSubstitutionCount1, evaluationProperties.tokenSubstitutionCount1) &&
        Objects.equals(this.tokenDeletionCount1, evaluationProperties.tokenDeletionCount1) &&
        Objects.equals(this.tokenInsertionCount1, evaluationProperties.tokenInsertionCount1) &&
        Objects.equals(this.tokenErrors1, evaluationProperties.tokenErrors1) &&
        Objects.equals(this.wordErrorRate2, evaluationProperties.wordErrorRate2) &&
        Objects.equals(this.sentenceErrorRate2, evaluationProperties.sentenceErrorRate2) &&
        Objects.equals(this.tokenErrorRate2, evaluationProperties.tokenErrorRate2) &&
        Objects.equals(this.sentenceCount2, evaluationProperties.sentenceCount2) &&
        Objects.equals(this.wordCount2, evaluationProperties.wordCount2) &&
        Objects.equals(this.correctWordCount2, evaluationProperties.correctWordCount2) &&
        Objects.equals(this.wordSubstitutionCount2, evaluationProperties.wordSubstitutionCount2) &&
        Objects.equals(this.wordDeletionCount2, evaluationProperties.wordDeletionCount2) &&
        Objects.equals(this.wordInsertionCount2, evaluationProperties.wordInsertionCount2) &&
        Objects.equals(this.tokenCount2, evaluationProperties.tokenCount2) &&
        Objects.equals(this.correctTokenCount2, evaluationProperties.correctTokenCount2) &&
        Objects.equals(this.tokenSubstitutionCount2, evaluationProperties.tokenSubstitutionCount2) &&
        Objects.equals(this.tokenDeletionCount2, evaluationProperties.tokenDeletionCount2) &&
        Objects.equals(this.tokenInsertionCount2, evaluationProperties.tokenInsertionCount2) &&
        Objects.equals(this.tokenErrors2, evaluationProperties.tokenErrors2) &&
        Objects.equals(this.email, evaluationProperties.email) &&
        Objects.equals(this.error, evaluationProperties.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wordErrorRate1, sentenceErrorRate1, tokenErrorRate1, sentenceCount1, wordCount1, correctWordCount1, wordSubstitutionCount1, wordDeletionCount1, wordInsertionCount1, tokenCount1, correctTokenCount1, tokenSubstitutionCount1, tokenDeletionCount1, tokenInsertionCount1, tokenErrors1, wordErrorRate2, sentenceErrorRate2, tokenErrorRate2, sentenceCount2, wordCount2, correctWordCount2, wordSubstitutionCount2, wordDeletionCount2, wordInsertionCount2, tokenCount2, correctTokenCount2, tokenSubstitutionCount2, tokenDeletionCount2, tokenInsertionCount2, tokenErrors2, email, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvaluationProperties {\n");
    sb.append("    wordErrorRate1: ").append(toIndentedString(wordErrorRate1)).append("\n");
    sb.append("    sentenceErrorRate1: ").append(toIndentedString(sentenceErrorRate1)).append("\n");
    sb.append("    tokenErrorRate1: ").append(toIndentedString(tokenErrorRate1)).append("\n");
    sb.append("    sentenceCount1: ").append(toIndentedString(sentenceCount1)).append("\n");
    sb.append("    wordCount1: ").append(toIndentedString(wordCount1)).append("\n");
    sb.append("    correctWordCount1: ").append(toIndentedString(correctWordCount1)).append("\n");
    sb.append("    wordSubstitutionCount1: ").append(toIndentedString(wordSubstitutionCount1)).append("\n");
    sb.append("    wordDeletionCount1: ").append(toIndentedString(wordDeletionCount1)).append("\n");
    sb.append("    wordInsertionCount1: ").append(toIndentedString(wordInsertionCount1)).append("\n");
    sb.append("    tokenCount1: ").append(toIndentedString(tokenCount1)).append("\n");
    sb.append("    correctTokenCount1: ").append(toIndentedString(correctTokenCount1)).append("\n");
    sb.append("    tokenSubstitutionCount1: ").append(toIndentedString(tokenSubstitutionCount1)).append("\n");
    sb.append("    tokenDeletionCount1: ").append(toIndentedString(tokenDeletionCount1)).append("\n");
    sb.append("    tokenInsertionCount1: ").append(toIndentedString(tokenInsertionCount1)).append("\n");
    sb.append("    tokenErrors1: ").append(toIndentedString(tokenErrors1)).append("\n");
    sb.append("    wordErrorRate2: ").append(toIndentedString(wordErrorRate2)).append("\n");
    sb.append("    sentenceErrorRate2: ").append(toIndentedString(sentenceErrorRate2)).append("\n");
    sb.append("    tokenErrorRate2: ").append(toIndentedString(tokenErrorRate2)).append("\n");
    sb.append("    sentenceCount2: ").append(toIndentedString(sentenceCount2)).append("\n");
    sb.append("    wordCount2: ").append(toIndentedString(wordCount2)).append("\n");
    sb.append("    correctWordCount2: ").append(toIndentedString(correctWordCount2)).append("\n");
    sb.append("    wordSubstitutionCount2: ").append(toIndentedString(wordSubstitutionCount2)).append("\n");
    sb.append("    wordDeletionCount2: ").append(toIndentedString(wordDeletionCount2)).append("\n");
    sb.append("    wordInsertionCount2: ").append(toIndentedString(wordInsertionCount2)).append("\n");
    sb.append("    tokenCount2: ").append(toIndentedString(tokenCount2)).append("\n");
    sb.append("    correctTokenCount2: ").append(toIndentedString(correctTokenCount2)).append("\n");
    sb.append("    tokenSubstitutionCount2: ").append(toIndentedString(tokenSubstitutionCount2)).append("\n");
    sb.append("    tokenDeletionCount2: ").append(toIndentedString(tokenDeletionCount2)).append("\n");
    sb.append("    tokenInsertionCount2: ").append(toIndentedString(tokenInsertionCount2)).append("\n");
    sb.append("    tokenErrors2: ").append(toIndentedString(tokenErrors2)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `wordErrorRate1` to the URL query string
    if (getWordErrorRate1() != null) {
      joiner.add(String.format("%swordErrorRate1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWordErrorRate1()))));
    }

    // add `sentenceErrorRate1` to the URL query string
    if (getSentenceErrorRate1() != null) {
      joiner.add(String.format("%ssentenceErrorRate1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSentenceErrorRate1()))));
    }

    // add `tokenErrorRate1` to the URL query string
    if (getTokenErrorRate1() != null) {
      joiner.add(String.format("%stokenErrorRate1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenErrorRate1()))));
    }

    // add `sentenceCount1` to the URL query string
    if (getSentenceCount1() != null) {
      joiner.add(String.format("%ssentenceCount1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSentenceCount1()))));
    }

    // add `wordCount1` to the URL query string
    if (getWordCount1() != null) {
      joiner.add(String.format("%swordCount1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWordCount1()))));
    }

    // add `correctWordCount1` to the URL query string
    if (getCorrectWordCount1() != null) {
      joiner.add(String.format("%scorrectWordCount1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCorrectWordCount1()))));
    }

    // add `wordSubstitutionCount1` to the URL query string
    if (getWordSubstitutionCount1() != null) {
      joiner.add(String.format("%swordSubstitutionCount1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWordSubstitutionCount1()))));
    }

    // add `wordDeletionCount1` to the URL query string
    if (getWordDeletionCount1() != null) {
      joiner.add(String.format("%swordDeletionCount1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWordDeletionCount1()))));
    }

    // add `wordInsertionCount1` to the URL query string
    if (getWordInsertionCount1() != null) {
      joiner.add(String.format("%swordInsertionCount1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWordInsertionCount1()))));
    }

    // add `tokenCount1` to the URL query string
    if (getTokenCount1() != null) {
      joiner.add(String.format("%stokenCount1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenCount1()))));
    }

    // add `correctTokenCount1` to the URL query string
    if (getCorrectTokenCount1() != null) {
      joiner.add(String.format("%scorrectTokenCount1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCorrectTokenCount1()))));
    }

    // add `tokenSubstitutionCount1` to the URL query string
    if (getTokenSubstitutionCount1() != null) {
      joiner.add(String.format("%stokenSubstitutionCount1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenSubstitutionCount1()))));
    }

    // add `tokenDeletionCount1` to the URL query string
    if (getTokenDeletionCount1() != null) {
      joiner.add(String.format("%stokenDeletionCount1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenDeletionCount1()))));
    }

    // add `tokenInsertionCount1` to the URL query string
    if (getTokenInsertionCount1() != null) {
      joiner.add(String.format("%stokenInsertionCount1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenInsertionCount1()))));
    }

    // add `tokenErrors1` to the URL query string
    if (getTokenErrors1() != null) {
      joiner.add(getTokenErrors1().toUrlQueryString(prefix + "tokenErrors1" + suffix));
    }

    // add `wordErrorRate2` to the URL query string
    if (getWordErrorRate2() != null) {
      joiner.add(String.format("%swordErrorRate2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWordErrorRate2()))));
    }

    // add `sentenceErrorRate2` to the URL query string
    if (getSentenceErrorRate2() != null) {
      joiner.add(String.format("%ssentenceErrorRate2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSentenceErrorRate2()))));
    }

    // add `tokenErrorRate2` to the URL query string
    if (getTokenErrorRate2() != null) {
      joiner.add(String.format("%stokenErrorRate2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenErrorRate2()))));
    }

    // add `sentenceCount2` to the URL query string
    if (getSentenceCount2() != null) {
      joiner.add(String.format("%ssentenceCount2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSentenceCount2()))));
    }

    // add `wordCount2` to the URL query string
    if (getWordCount2() != null) {
      joiner.add(String.format("%swordCount2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWordCount2()))));
    }

    // add `correctWordCount2` to the URL query string
    if (getCorrectWordCount2() != null) {
      joiner.add(String.format("%scorrectWordCount2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCorrectWordCount2()))));
    }

    // add `wordSubstitutionCount2` to the URL query string
    if (getWordSubstitutionCount2() != null) {
      joiner.add(String.format("%swordSubstitutionCount2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWordSubstitutionCount2()))));
    }

    // add `wordDeletionCount2` to the URL query string
    if (getWordDeletionCount2() != null) {
      joiner.add(String.format("%swordDeletionCount2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWordDeletionCount2()))));
    }

    // add `wordInsertionCount2` to the URL query string
    if (getWordInsertionCount2() != null) {
      joiner.add(String.format("%swordInsertionCount2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWordInsertionCount2()))));
    }

    // add `tokenCount2` to the URL query string
    if (getTokenCount2() != null) {
      joiner.add(String.format("%stokenCount2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenCount2()))));
    }

    // add `correctTokenCount2` to the URL query string
    if (getCorrectTokenCount2() != null) {
      joiner.add(String.format("%scorrectTokenCount2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCorrectTokenCount2()))));
    }

    // add `tokenSubstitutionCount2` to the URL query string
    if (getTokenSubstitutionCount2() != null) {
      joiner.add(String.format("%stokenSubstitutionCount2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenSubstitutionCount2()))));
    }

    // add `tokenDeletionCount2` to the URL query string
    if (getTokenDeletionCount2() != null) {
      joiner.add(String.format("%stokenDeletionCount2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenDeletionCount2()))));
    }

    // add `tokenInsertionCount2` to the URL query string
    if (getTokenInsertionCount2() != null) {
      joiner.add(String.format("%stokenInsertionCount2%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenInsertionCount2()))));
    }

    // add `tokenErrors2` to the URL query string
    if (getTokenErrors2() != null) {
      joiner.add(getTokenErrors2().toUrlQueryString(prefix + "tokenErrors2" + suffix));
    }

    // add `email` to the URL query string
    if (getEmail() != null) {
      joiner.add(String.format("%semail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmail()))));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(getError().toUrlQueryString(prefix + "error" + suffix));
    }

    return joiner.toString();
  }

    public static class Builder {

    private EvaluationProperties instance;

    public Builder() {
      this(new EvaluationProperties());
    }

    protected Builder(EvaluationProperties instance) {
      this.instance = instance;
    }

    public EvaluationProperties.Builder wordErrorRate1(Double wordErrorRate1) {
      this.instance.wordErrorRate1 = wordErrorRate1;
      return this;
    }
    public EvaluationProperties.Builder sentenceErrorRate1(Double sentenceErrorRate1) {
      this.instance.sentenceErrorRate1 = sentenceErrorRate1;
      return this;
    }
    public EvaluationProperties.Builder tokenErrorRate1(Double tokenErrorRate1) {
      this.instance.tokenErrorRate1 = tokenErrorRate1;
      return this;
    }
    public EvaluationProperties.Builder sentenceCount1(Integer sentenceCount1) {
      this.instance.sentenceCount1 = sentenceCount1;
      return this;
    }
    public EvaluationProperties.Builder wordCount1(Integer wordCount1) {
      this.instance.wordCount1 = wordCount1;
      return this;
    }
    public EvaluationProperties.Builder correctWordCount1(Integer correctWordCount1) {
      this.instance.correctWordCount1 = correctWordCount1;
      return this;
    }
    public EvaluationProperties.Builder wordSubstitutionCount1(Integer wordSubstitutionCount1) {
      this.instance.wordSubstitutionCount1 = wordSubstitutionCount1;
      return this;
    }
    public EvaluationProperties.Builder wordDeletionCount1(Integer wordDeletionCount1) {
      this.instance.wordDeletionCount1 = wordDeletionCount1;
      return this;
    }
    public EvaluationProperties.Builder wordInsertionCount1(Integer wordInsertionCount1) {
      this.instance.wordInsertionCount1 = wordInsertionCount1;
      return this;
    }
    public EvaluationProperties.Builder tokenCount1(Integer tokenCount1) {
      this.instance.tokenCount1 = tokenCount1;
      return this;
    }
    public EvaluationProperties.Builder correctTokenCount1(Integer correctTokenCount1) {
      this.instance.correctTokenCount1 = correctTokenCount1;
      return this;
    }
    public EvaluationProperties.Builder tokenSubstitutionCount1(Integer tokenSubstitutionCount1) {
      this.instance.tokenSubstitutionCount1 = tokenSubstitutionCount1;
      return this;
    }
    public EvaluationProperties.Builder tokenDeletionCount1(Integer tokenDeletionCount1) {
      this.instance.tokenDeletionCount1 = tokenDeletionCount1;
      return this;
    }
    public EvaluationProperties.Builder tokenInsertionCount1(Integer tokenInsertionCount1) {
      this.instance.tokenInsertionCount1 = tokenInsertionCount1;
      return this;
    }
    public EvaluationProperties.Builder tokenErrors1(TokenErrorDetails tokenErrors1) {
      this.instance.tokenErrors1 = tokenErrors1;
      return this;
    }
    public EvaluationProperties.Builder wordErrorRate2(Double wordErrorRate2) {
      this.instance.wordErrorRate2 = wordErrorRate2;
      return this;
    }
    public EvaluationProperties.Builder sentenceErrorRate2(Double sentenceErrorRate2) {
      this.instance.sentenceErrorRate2 = sentenceErrorRate2;
      return this;
    }
    public EvaluationProperties.Builder tokenErrorRate2(Double tokenErrorRate2) {
      this.instance.tokenErrorRate2 = tokenErrorRate2;
      return this;
    }
    public EvaluationProperties.Builder sentenceCount2(Integer sentenceCount2) {
      this.instance.sentenceCount2 = sentenceCount2;
      return this;
    }
    public EvaluationProperties.Builder wordCount2(Integer wordCount2) {
      this.instance.wordCount2 = wordCount2;
      return this;
    }
    public EvaluationProperties.Builder correctWordCount2(Integer correctWordCount2) {
      this.instance.correctWordCount2 = correctWordCount2;
      return this;
    }
    public EvaluationProperties.Builder wordSubstitutionCount2(Integer wordSubstitutionCount2) {
      this.instance.wordSubstitutionCount2 = wordSubstitutionCount2;
      return this;
    }
    public EvaluationProperties.Builder wordDeletionCount2(Integer wordDeletionCount2) {
      this.instance.wordDeletionCount2 = wordDeletionCount2;
      return this;
    }
    public EvaluationProperties.Builder wordInsertionCount2(Integer wordInsertionCount2) {
      this.instance.wordInsertionCount2 = wordInsertionCount2;
      return this;
    }
    public EvaluationProperties.Builder tokenCount2(Integer tokenCount2) {
      this.instance.tokenCount2 = tokenCount2;
      return this;
    }
    public EvaluationProperties.Builder correctTokenCount2(Integer correctTokenCount2) {
      this.instance.correctTokenCount2 = correctTokenCount2;
      return this;
    }
    public EvaluationProperties.Builder tokenSubstitutionCount2(Integer tokenSubstitutionCount2) {
      this.instance.tokenSubstitutionCount2 = tokenSubstitutionCount2;
      return this;
    }
    public EvaluationProperties.Builder tokenDeletionCount2(Integer tokenDeletionCount2) {
      this.instance.tokenDeletionCount2 = tokenDeletionCount2;
      return this;
    }
    public EvaluationProperties.Builder tokenInsertionCount2(Integer tokenInsertionCount2) {
      this.instance.tokenInsertionCount2 = tokenInsertionCount2;
      return this;
    }
    public EvaluationProperties.Builder tokenErrors2(TokenErrorDetails tokenErrors2) {
      this.instance.tokenErrors2 = tokenErrors2;
      return this;
    }
    public EvaluationProperties.Builder email(String email) {
      this.instance.email = email;
      return this;
    }
    public EvaluationProperties.Builder error(EntityError error) {
      this.instance.error = error;
      return this;
    }


    /**
    * returns a built EvaluationProperties instance.
    *
    * The builder is not reusable.
    */
    public EvaluationProperties build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static EvaluationProperties.Builder builder() {
    return new EvaluationProperties.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public EvaluationProperties.Builder toBuilder() {
    return new EvaluationProperties.Builder()
      .wordErrorRate1(getWordErrorRate1())
      .sentenceErrorRate1(getSentenceErrorRate1())
      .tokenErrorRate1(getTokenErrorRate1())
      .sentenceCount1(getSentenceCount1())
      .wordCount1(getWordCount1())
      .correctWordCount1(getCorrectWordCount1())
      .wordSubstitutionCount1(getWordSubstitutionCount1())
      .wordDeletionCount1(getWordDeletionCount1())
      .wordInsertionCount1(getWordInsertionCount1())
      .tokenCount1(getTokenCount1())
      .correctTokenCount1(getCorrectTokenCount1())
      .tokenSubstitutionCount1(getTokenSubstitutionCount1())
      .tokenDeletionCount1(getTokenDeletionCount1())
      .tokenInsertionCount1(getTokenInsertionCount1())
      .tokenErrors1(getTokenErrors1())
      .wordErrorRate2(getWordErrorRate2())
      .sentenceErrorRate2(getSentenceErrorRate2())
      .tokenErrorRate2(getTokenErrorRate2())
      .sentenceCount2(getSentenceCount2())
      .wordCount2(getWordCount2())
      .correctWordCount2(getCorrectWordCount2())
      .wordSubstitutionCount2(getWordSubstitutionCount2())
      .wordDeletionCount2(getWordDeletionCount2())
      .wordInsertionCount2(getWordInsertionCount2())
      .tokenCount2(getTokenCount2())
      .correctTokenCount2(getCorrectTokenCount2())
      .tokenSubstitutionCount2(getTokenSubstitutionCount2())
      .tokenDeletionCount2(getTokenDeletionCount2())
      .tokenInsertionCount2(getTokenInsertionCount2())
      .tokenErrors2(getTokenErrors2())
      .email(getEmail())
      .error(getError());
  }

}

