/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * ModelFile
 */
@JsonPropertyOrder({
  ModelFile.JSON_PROPERTY_NAME,
  ModelFile.JSON_PROPERTY_CONTENT_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T10:07:46.057250+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class ModelFile {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_CONTENT_URL = "contentUrl";
  @javax.annotation.Nullable
  private URI contentUrl;

  public ModelFile() { 
  }

  @JsonCreator
  public ModelFile(
    @JsonProperty(JSON_PROPERTY_NAME) String name, 
    @JsonProperty(JSON_PROPERTY_CONTENT_URL) URI contentUrl
  ) {
  this();
    this.name = name;
    this.contentUrl = contentUrl;
  }

  /**
   * The name of this file.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }




  /**
   * The url to retrieve the content of this file.
   * @return contentUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getContentUrl() {
    return contentUrl;
  }




  /**
   * Return true if this ModelFile object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelFile modelFile = (ModelFile) o;
    return Objects.equals(this.name, modelFile.name) &&
        Objects.equals(this.contentUrl, modelFile.contentUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, contentUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelFile {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    contentUrl: ").append(toIndentedString(contentUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `contentUrl` to the URL query string
    if (getContentUrl() != null) {
      joiner.add(String.format("%scontentUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContentUrl()))));
    }

    return joiner.toString();
  }

    public static class Builder {

    private ModelFile instance;

    public Builder() {
      this(new ModelFile());
    }

    protected Builder(ModelFile instance) {
      this.instance = instance;
    }

    public ModelFile.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public ModelFile.Builder contentUrl(URI contentUrl) {
      this.instance.contentUrl = contentUrl;
      return this;
    }


    /**
    * returns a built ModelFile instance.
    *
    * The builder is not reusable.
    */
    public ModelFile build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ModelFile.Builder builder() {
    return new ModelFile.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ModelFile.Builder toBuilder() {
    return new ModelFile.Builder()
      .name(getName())
      .contentUrl(getContentUrl());
  }

}

