/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Evaluation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * PaginatedEvaluations
 */
@JsonPropertyOrder({
  PaginatedEvaluations.JSON_PROPERTY_VALUES,
  PaginatedEvaluations.JSON_PROPERTY_AT_NEXT_LINK
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T10:07:46.057250+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class PaginatedEvaluations {
  public static final String JSON_PROPERTY_VALUES = "values";
  @javax.annotation.Nullable
  private List<Evaluation> values = new ArrayList<>();

  public static final String JSON_PROPERTY_AT_NEXT_LINK = "@nextLink";
  @javax.annotation.Nullable
  private URI atNextLink;

  public PaginatedEvaluations() { 
  }

  @JsonCreator
  public PaginatedEvaluations(
    @JsonProperty(JSON_PROPERTY_VALUES) List<Evaluation> values, 
    @JsonProperty(JSON_PROPERTY_AT_NEXT_LINK) URI atNextLink
  ) {
  this();
    this.values = values;
    this.atNextLink = atNextLink;
  }

  /**
   * A list of entities limited by either the passed query parameters &#39;skip&#39; and &#39;top&#39; or their default values.                When iterating through a list using pagination and deleting entities in parallel, some entities will be skipped in the results.  It&#39;s recommended to build a list on the client and delete after the fetching of the complete list.
   * @return values
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Evaluation> getValues() {
    return values;
  }




  /**
   * A link to the next set of paginated results if there are more entities available; otherwise null.
   * @return atNextLink
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AT_NEXT_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getAtNextLink() {
    return atNextLink;
  }




  /**
   * Return true if this PaginatedEvaluations object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginatedEvaluations paginatedEvaluations = (PaginatedEvaluations) o;
    return Objects.equals(this.values, paginatedEvaluations.values) &&
        Objects.equals(this.atNextLink, paginatedEvaluations.atNextLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(values, atNextLink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginatedEvaluations {\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    atNextLink: ").append(toIndentedString(atNextLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `values` to the URL query string
    if (getValues() != null) {
      for (int i = 0; i < getValues().size(); i++) {
        if (getValues().get(i) != null) {
          joiner.add(getValues().get(i).toUrlQueryString(String.format("%svalues%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `@nextLink` to the URL query string
    if (getAtNextLink() != null) {
      joiner.add(String.format("%s@nextLink%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAtNextLink()))));
    }

    return joiner.toString();
  }

    public static class Builder {

    private PaginatedEvaluations instance;

    public Builder() {
      this(new PaginatedEvaluations());
    }

    protected Builder(PaginatedEvaluations instance) {
      this.instance = instance;
    }

    public PaginatedEvaluations.Builder values(List<Evaluation> values) {
      this.instance.values = values;
      return this;
    }
    public PaginatedEvaluations.Builder atNextLink(URI atNextLink) {
      this.instance.atNextLink = atNextLink;
      return this;
    }


    /**
    * returns a built PaginatedEvaluations instance.
    *
    * The builder is not reusable.
    */
    public PaginatedEvaluations build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static PaginatedEvaluations.Builder builder() {
    return new PaginatedEvaluations.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public PaginatedEvaluations.Builder toBuilder() {
    return new PaginatedEvaluations.Builder()
      .values(getValues())
      .atNextLink(getAtNextLink());
  }

}

