/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DiarizationProperties;
import org.openapitools.client.model.EntityError;
import org.openapitools.client.model.LanguageIdentificationProperties;
import org.openapitools.client.model.ProfanityFilterMode;
import org.openapitools.client.model.PunctuationMode;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * TranscriptionProperties
 */
@JsonPropertyOrder({
  TranscriptionProperties.JSON_PROPERTY_WORD_LEVEL_TIMESTAMPS_ENABLED,
  TranscriptionProperties.JSON_PROPERTY_DISPLAY_FORM_WORD_LEVEL_TIMESTAMPS_ENABLED,
  TranscriptionProperties.JSON_PROPERTY_DURATION,
  TranscriptionProperties.JSON_PROPERTY_CHANNELS,
  TranscriptionProperties.JSON_PROPERTY_DESTINATION_CONTAINER_URL,
  TranscriptionProperties.JSON_PROPERTY_PUNCTUATION_MODE,
  TranscriptionProperties.JSON_PROPERTY_PROFANITY_FILTER_MODE,
  TranscriptionProperties.JSON_PROPERTY_TIME_TO_LIVE,
  TranscriptionProperties.JSON_PROPERTY_EMAIL,
  TranscriptionProperties.JSON_PROPERTY_ERROR,
  TranscriptionProperties.JSON_PROPERTY_DIARIZATION_ENABLED,
  TranscriptionProperties.JSON_PROPERTY_DIARIZATION,
  TranscriptionProperties.JSON_PROPERTY_LANGUAGE_IDENTIFICATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T10:07:46.057250+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class TranscriptionProperties {
  public static final String JSON_PROPERTY_WORD_LEVEL_TIMESTAMPS_ENABLED = "wordLevelTimestampsEnabled";
  @javax.annotation.Nullable
  private Boolean wordLevelTimestampsEnabled;

  public static final String JSON_PROPERTY_DISPLAY_FORM_WORD_LEVEL_TIMESTAMPS_ENABLED = "displayFormWordLevelTimestampsEnabled";
  @javax.annotation.Nullable
  private Boolean displayFormWordLevelTimestampsEnabled;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @javax.annotation.Nullable
  private String duration;

  public static final String JSON_PROPERTY_CHANNELS = "channels";
  @javax.annotation.Nullable
  private List<Integer> channels = new ArrayList<>();

  public static final String JSON_PROPERTY_DESTINATION_CONTAINER_URL = "destinationContainerUrl";
  @javax.annotation.Nullable
  private URI destinationContainerUrl;

  public static final String JSON_PROPERTY_PUNCTUATION_MODE = "punctuationMode";
  @javax.annotation.Nullable
  private PunctuationMode punctuationMode;

  public static final String JSON_PROPERTY_PROFANITY_FILTER_MODE = "profanityFilterMode";
  @javax.annotation.Nullable
  private ProfanityFilterMode profanityFilterMode;

  public static final String JSON_PROPERTY_TIME_TO_LIVE = "timeToLive";
  @javax.annotation.Nullable
  private String timeToLive;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_ERROR = "error";
  @javax.annotation.Nullable
  private EntityError error;

  public static final String JSON_PROPERTY_DIARIZATION_ENABLED = "diarizationEnabled";
  @javax.annotation.Nullable
  private Boolean diarizationEnabled;

  public static final String JSON_PROPERTY_DIARIZATION = "diarization";
  @javax.annotation.Nullable
  private DiarizationProperties diarization;

  public static final String JSON_PROPERTY_LANGUAGE_IDENTIFICATION = "languageIdentification";
  @javax.annotation.Nullable
  private LanguageIdentificationProperties languageIdentification;

  public TranscriptionProperties() { 
  }

  @JsonCreator
  public TranscriptionProperties(
    @JsonProperty(JSON_PROPERTY_DURATION) String duration
  ) {
  this();
    this.duration = duration;
  }

  public TranscriptionProperties wordLevelTimestampsEnabled(@javax.annotation.Nullable Boolean wordLevelTimestampsEnabled) {
    this.wordLevelTimestampsEnabled = wordLevelTimestampsEnabled;
    return this;
  }

  /**
   * A value indicating whether word level timestamps are requested. The default value is  &#x60;false&#x60;.
   * @return wordLevelTimestampsEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORD_LEVEL_TIMESTAMPS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getWordLevelTimestampsEnabled() {
    return wordLevelTimestampsEnabled;
  }


  @JsonProperty(JSON_PROPERTY_WORD_LEVEL_TIMESTAMPS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWordLevelTimestampsEnabled(@javax.annotation.Nullable Boolean wordLevelTimestampsEnabled) {
    this.wordLevelTimestampsEnabled = wordLevelTimestampsEnabled;
  }


  public TranscriptionProperties displayFormWordLevelTimestampsEnabled(@javax.annotation.Nullable Boolean displayFormWordLevelTimestampsEnabled) {
    this.displayFormWordLevelTimestampsEnabled = displayFormWordLevelTimestampsEnabled;
    return this;
  }

  /**
   * A value indicating whether word level timestamps for the display form are requested. The default value is &#x60;false&#x60;.
   * @return displayFormWordLevelTimestampsEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_FORM_WORD_LEVEL_TIMESTAMPS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDisplayFormWordLevelTimestampsEnabled() {
    return displayFormWordLevelTimestampsEnabled;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_FORM_WORD_LEVEL_TIMESTAMPS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayFormWordLevelTimestampsEnabled(@javax.annotation.Nullable Boolean displayFormWordLevelTimestampsEnabled) {
    this.displayFormWordLevelTimestampsEnabled = displayFormWordLevelTimestampsEnabled;
  }


  /**
   * The duration of the transcription. The duration is encoded as ISO 8601 duration  (\&quot;PnYnMnDTnHnMnS\&quot;, see https://en.wikipedia.org/wiki/ISO_8601#Durations).
   * @return duration
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDuration() {
    return duration;
  }




  public TranscriptionProperties channels(@javax.annotation.Nullable List<Integer> channels) {
    this.channels = channels;
    return this;
  }

  public TranscriptionProperties addChannelsItem(Integer channelsItem) {
    if (this.channels == null) {
      this.channels = new ArrayList<>();
    }
    this.channels.add(channelsItem);
    return this;
  }

  /**
   * A collection of the requested channel numbers.  In the default case, the channels 0 and 1 are considered.
   * @return channels
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHANNELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Integer> getChannels() {
    return channels;
  }


  @JsonProperty(JSON_PROPERTY_CHANNELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChannels(@javax.annotation.Nullable List<Integer> channels) {
    this.channels = channels;
  }


  public TranscriptionProperties destinationContainerUrl(@javax.annotation.Nullable URI destinationContainerUrl) {
    this.destinationContainerUrl = destinationContainerUrl;
    return this;
  }

  /**
   * The requested destination container.  ### Remarks ###  When a destination container is used in combination with a &#x60;timeToLive&#x60;, the metadata of a  transcription will be deleted normally, but the data stored in the destination container, including  transcription results, will remain untouched, because no delete permissions are required for this  container.&lt;br /&gt;  To support automatic cleanup, either configure blob lifetimes on the container, or use \&quot;Bring your own Storage (BYOS)\&quot;  instead of &#x60;destinationContainerUrl&#x60;, where blobs can be cleaned up.
   * @return destinationContainerUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESTINATION_CONTAINER_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getDestinationContainerUrl() {
    return destinationContainerUrl;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATION_CONTAINER_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationContainerUrl(@javax.annotation.Nullable URI destinationContainerUrl) {
    this.destinationContainerUrl = destinationContainerUrl;
  }


  public TranscriptionProperties punctuationMode(@javax.annotation.Nullable PunctuationMode punctuationMode) {
    this.punctuationMode = punctuationMode;
    return this;
  }

  /**
   * Get punctuationMode
   * @return punctuationMode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUNCTUATION_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PunctuationMode getPunctuationMode() {
    return punctuationMode;
  }


  @JsonProperty(JSON_PROPERTY_PUNCTUATION_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPunctuationMode(@javax.annotation.Nullable PunctuationMode punctuationMode) {
    this.punctuationMode = punctuationMode;
  }


  public TranscriptionProperties profanityFilterMode(@javax.annotation.Nullable ProfanityFilterMode profanityFilterMode) {
    this.profanityFilterMode = profanityFilterMode;
    return this;
  }

  /**
   * Get profanityFilterMode
   * @return profanityFilterMode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFANITY_FILTER_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProfanityFilterMode getProfanityFilterMode() {
    return profanityFilterMode;
  }


  @JsonProperty(JSON_PROPERTY_PROFANITY_FILTER_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfanityFilterMode(@javax.annotation.Nullable ProfanityFilterMode profanityFilterMode) {
    this.profanityFilterMode = profanityFilterMode;
  }


  public TranscriptionProperties timeToLive(@javax.annotation.Nullable String timeToLive) {
    this.timeToLive = timeToLive;
    return this;
  }

  /**
   * How long the transcription will be kept in the system after it has completed. Once the  transcription reaches the time to live after completion (successful or failed) it will be automatically  deleted. Not setting this value or setting it to 0 will disable automatic deletion. The longest supported  duration is 31 days.  The duration is encoded as ISO 8601 duration (\&quot;PnYnMnDTnHnMnS\&quot;, see https://en.wikipedia.org/wiki/ISO_8601#Durations).
   * @return timeToLive
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_TO_LIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimeToLive() {
    return timeToLive;
  }


  @JsonProperty(JSON_PROPERTY_TIME_TO_LIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeToLive(@javax.annotation.Nullable String timeToLive) {
    this.timeToLive = timeToLive;
  }


  public TranscriptionProperties email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * The email address to send email notifications to in case the operation completes.  The value will be removed after successfully sending the email.
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public TranscriptionProperties error(@javax.annotation.Nullable EntityError error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EntityError getError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@javax.annotation.Nullable EntityError error) {
    this.error = error;
  }


  public TranscriptionProperties diarizationEnabled(@javax.annotation.Nullable Boolean diarizationEnabled) {
    this.diarizationEnabled = diarizationEnabled;
    return this;
  }

  /**
   * A value indicating whether diarization (speaker identification) is requested. The default value  is &#x60;false&#x60;.  If this field is set to true and the improved diarization system is configured by specifying  &#x60;DiarizationProperties&#x60;, the improved diarization system will provide diarization for a configurable  range of speakers.  If this field is set to true and the improved diarization system is not enabled (not specifying  &#x60;DiarizationProperties&#x60;), the basic diarization system will distinguish between up to two speakers.  No extra charges are applied for the basic diarization.                The basic diarization system is deprecated and will be removed in the next major version of the API.  This &#x60;diarizationEnabled&#x60; setting will also be removed.
   * @return diarizationEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIARIZATION_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDiarizationEnabled() {
    return diarizationEnabled;
  }


  @JsonProperty(JSON_PROPERTY_DIARIZATION_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiarizationEnabled(@javax.annotation.Nullable Boolean diarizationEnabled) {
    this.diarizationEnabled = diarizationEnabled;
  }


  public TranscriptionProperties diarization(@javax.annotation.Nullable DiarizationProperties diarization) {
    this.diarization = diarization;
    return this;
  }

  /**
   * Get diarization
   * @return diarization
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIARIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DiarizationProperties getDiarization() {
    return diarization;
  }


  @JsonProperty(JSON_PROPERTY_DIARIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiarization(@javax.annotation.Nullable DiarizationProperties diarization) {
    this.diarization = diarization;
  }


  public TranscriptionProperties languageIdentification(@javax.annotation.Nullable LanguageIdentificationProperties languageIdentification) {
    this.languageIdentification = languageIdentification;
    return this;
  }

  /**
   * Get languageIdentification
   * @return languageIdentification
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LANGUAGE_IDENTIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LanguageIdentificationProperties getLanguageIdentification() {
    return languageIdentification;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE_IDENTIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguageIdentification(@javax.annotation.Nullable LanguageIdentificationProperties languageIdentification) {
    this.languageIdentification = languageIdentification;
  }


  /**
   * Return true if this TranscriptionProperties object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranscriptionProperties transcriptionProperties = (TranscriptionProperties) o;
    return Objects.equals(this.wordLevelTimestampsEnabled, transcriptionProperties.wordLevelTimestampsEnabled) &&
        Objects.equals(this.displayFormWordLevelTimestampsEnabled, transcriptionProperties.displayFormWordLevelTimestampsEnabled) &&
        Objects.equals(this.duration, transcriptionProperties.duration) &&
        Objects.equals(this.channels, transcriptionProperties.channels) &&
        Objects.equals(this.destinationContainerUrl, transcriptionProperties.destinationContainerUrl) &&
        Objects.equals(this.punctuationMode, transcriptionProperties.punctuationMode) &&
        Objects.equals(this.profanityFilterMode, transcriptionProperties.profanityFilterMode) &&
        Objects.equals(this.timeToLive, transcriptionProperties.timeToLive) &&
        Objects.equals(this.email, transcriptionProperties.email) &&
        Objects.equals(this.error, transcriptionProperties.error) &&
        Objects.equals(this.diarizationEnabled, transcriptionProperties.diarizationEnabled) &&
        Objects.equals(this.diarization, transcriptionProperties.diarization) &&
        Objects.equals(this.languageIdentification, transcriptionProperties.languageIdentification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wordLevelTimestampsEnabled, displayFormWordLevelTimestampsEnabled, duration, channels, destinationContainerUrl, punctuationMode, profanityFilterMode, timeToLive, email, error, diarizationEnabled, diarization, languageIdentification);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranscriptionProperties {\n");
    sb.append("    wordLevelTimestampsEnabled: ").append(toIndentedString(wordLevelTimestampsEnabled)).append("\n");
    sb.append("    displayFormWordLevelTimestampsEnabled: ").append(toIndentedString(displayFormWordLevelTimestampsEnabled)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("    destinationContainerUrl: ").append(toIndentedString(destinationContainerUrl)).append("\n");
    sb.append("    punctuationMode: ").append(toIndentedString(punctuationMode)).append("\n");
    sb.append("    profanityFilterMode: ").append(toIndentedString(profanityFilterMode)).append("\n");
    sb.append("    timeToLive: ").append(toIndentedString(timeToLive)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    diarizationEnabled: ").append(toIndentedString(diarizationEnabled)).append("\n");
    sb.append("    diarization: ").append(toIndentedString(diarization)).append("\n");
    sb.append("    languageIdentification: ").append(toIndentedString(languageIdentification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `wordLevelTimestampsEnabled` to the URL query string
    if (getWordLevelTimestampsEnabled() != null) {
      joiner.add(String.format("%swordLevelTimestampsEnabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWordLevelTimestampsEnabled()))));
    }

    // add `displayFormWordLevelTimestampsEnabled` to the URL query string
    if (getDisplayFormWordLevelTimestampsEnabled() != null) {
      joiner.add(String.format("%sdisplayFormWordLevelTimestampsEnabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisplayFormWordLevelTimestampsEnabled()))));
    }

    // add `duration` to the URL query string
    if (getDuration() != null) {
      joiner.add(String.format("%sduration%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDuration()))));
    }

    // add `channels` to the URL query string
    if (getChannels() != null) {
      for (int i = 0; i < getChannels().size(); i++) {
        joiner.add(String.format("%schannels%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getChannels().get(i)))));
      }
    }

    // add `destinationContainerUrl` to the URL query string
    if (getDestinationContainerUrl() != null) {
      joiner.add(String.format("%sdestinationContainerUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDestinationContainerUrl()))));
    }

    // add `punctuationMode` to the URL query string
    if (getPunctuationMode() != null) {
      joiner.add(String.format("%spunctuationMode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPunctuationMode()))));
    }

    // add `profanityFilterMode` to the URL query string
    if (getProfanityFilterMode() != null) {
      joiner.add(String.format("%sprofanityFilterMode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProfanityFilterMode()))));
    }

    // add `timeToLive` to the URL query string
    if (getTimeToLive() != null) {
      joiner.add(String.format("%stimeToLive%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeToLive()))));
    }

    // add `email` to the URL query string
    if (getEmail() != null) {
      joiner.add(String.format("%semail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmail()))));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(getError().toUrlQueryString(prefix + "error" + suffix));
    }

    // add `diarizationEnabled` to the URL query string
    if (getDiarizationEnabled() != null) {
      joiner.add(String.format("%sdiarizationEnabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDiarizationEnabled()))));
    }

    // add `diarization` to the URL query string
    if (getDiarization() != null) {
      joiner.add(getDiarization().toUrlQueryString(prefix + "diarization" + suffix));
    }

    // add `languageIdentification` to the URL query string
    if (getLanguageIdentification() != null) {
      joiner.add(getLanguageIdentification().toUrlQueryString(prefix + "languageIdentification" + suffix));
    }

    return joiner.toString();
  }

    public static class Builder {

    private TranscriptionProperties instance;

    public Builder() {
      this(new TranscriptionProperties());
    }

    protected Builder(TranscriptionProperties instance) {
      this.instance = instance;
    }

    public TranscriptionProperties.Builder wordLevelTimestampsEnabled(Boolean wordLevelTimestampsEnabled) {
      this.instance.wordLevelTimestampsEnabled = wordLevelTimestampsEnabled;
      return this;
    }
    public TranscriptionProperties.Builder displayFormWordLevelTimestampsEnabled(Boolean displayFormWordLevelTimestampsEnabled) {
      this.instance.displayFormWordLevelTimestampsEnabled = displayFormWordLevelTimestampsEnabled;
      return this;
    }
    public TranscriptionProperties.Builder duration(String duration) {
      this.instance.duration = duration;
      return this;
    }
    public TranscriptionProperties.Builder channels(List<Integer> channels) {
      this.instance.channels = channels;
      return this;
    }
    public TranscriptionProperties.Builder destinationContainerUrl(URI destinationContainerUrl) {
      this.instance.destinationContainerUrl = destinationContainerUrl;
      return this;
    }
    public TranscriptionProperties.Builder punctuationMode(PunctuationMode punctuationMode) {
      this.instance.punctuationMode = punctuationMode;
      return this;
    }
    public TranscriptionProperties.Builder profanityFilterMode(ProfanityFilterMode profanityFilterMode) {
      this.instance.profanityFilterMode = profanityFilterMode;
      return this;
    }
    public TranscriptionProperties.Builder timeToLive(String timeToLive) {
      this.instance.timeToLive = timeToLive;
      return this;
    }
    public TranscriptionProperties.Builder email(String email) {
      this.instance.email = email;
      return this;
    }
    public TranscriptionProperties.Builder error(EntityError error) {
      this.instance.error = error;
      return this;
    }
    public TranscriptionProperties.Builder diarizationEnabled(Boolean diarizationEnabled) {
      this.instance.diarizationEnabled = diarizationEnabled;
      return this;
    }
    public TranscriptionProperties.Builder diarization(DiarizationProperties diarization) {
      this.instance.diarization = diarization;
      return this;
    }
    public TranscriptionProperties.Builder languageIdentification(LanguageIdentificationProperties languageIdentification) {
      this.instance.languageIdentification = languageIdentification;
      return this;
    }


    /**
    * returns a built TranscriptionProperties instance.
    *
    * The builder is not reusable.
    */
    public TranscriptionProperties build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static TranscriptionProperties.Builder builder() {
    return new TranscriptionProperties.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public TranscriptionProperties.Builder toBuilder() {
    return new TranscriptionProperties.Builder()
      .wordLevelTimestampsEnabled(getWordLevelTimestampsEnabled())
      .displayFormWordLevelTimestampsEnabled(getDisplayFormWordLevelTimestampsEnabled())
      .duration(getDuration())
      .channels(getChannels())
      .destinationContainerUrl(getDestinationContainerUrl())
      .punctuationMode(getPunctuationMode())
      .profanityFilterMode(getProfanityFilterMode())
      .timeToLive(getTimeToLive())
      .email(getEmail())
      .error(getError())
      .diarizationEnabled(getDiarizationEnabled())
      .diarization(getDiarization())
      .languageIdentification(getLanguageIdentification());
  }

}

