/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.WebHookEvents;
import org.openapitools.client.model.WebHookPropertiesUpdate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * WebHookUpdate
 */
@JsonPropertyOrder({
  WebHookUpdate.JSON_PROPERTY_WEB_URL,
  WebHookUpdate.JSON_PROPERTY_PROPERTIES,
  WebHookUpdate.JSON_PROPERTY_EVENTS,
  WebHookUpdate.JSON_PROPERTY_DISPLAY_NAME,
  WebHookUpdate.JSON_PROPERTY_DESCRIPTION,
  WebHookUpdate.JSON_PROPERTY_CUSTOM_PROPERTIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T10:07:46.057250+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class WebHookUpdate {
  public static final String JSON_PROPERTY_WEB_URL = "webUrl";
  @javax.annotation.Nullable
  private URI webUrl;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @javax.annotation.Nullable
  private WebHookPropertiesUpdate properties;

  public static final String JSON_PROPERTY_EVENTS = "events";
  @javax.annotation.Nullable
  private WebHookEvents events;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @javax.annotation.Nullable
  private String displayName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_CUSTOM_PROPERTIES = "customProperties";
  @javax.annotation.Nullable
  private Map<String, String> customProperties = new HashMap<>();

  public WebHookUpdate() { 
  }

  public WebHookUpdate webUrl(@javax.annotation.Nullable URI webUrl) {
    this.webUrl = webUrl;
    return this;
  }

  /**
   * The registered URL that will be used to send the POST requests for the registered events to.
   * @return webUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEB_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getWebUrl() {
    return webUrl;
  }


  @JsonProperty(JSON_PROPERTY_WEB_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebUrl(@javax.annotation.Nullable URI webUrl) {
    this.webUrl = webUrl;
  }


  public WebHookUpdate properties(@javax.annotation.Nullable WebHookPropertiesUpdate properties) {
    this.properties = properties;
    return this;
  }

  /**
   * Get properties
   * @return properties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WebHookPropertiesUpdate getProperties() {
    return properties;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperties(@javax.annotation.Nullable WebHookPropertiesUpdate properties) {
    this.properties = properties;
  }


  public WebHookUpdate events(@javax.annotation.Nullable WebHookEvents events) {
    this.events = events;
    return this;
  }

  /**
   * Get events
   * @return events
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WebHookEvents getEvents() {
    return events;
  }


  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvents(@javax.annotation.Nullable WebHookEvents events) {
    this.events = events;
  }


  public WebHookUpdate displayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * The name of the object.
   * @return displayName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }


  public WebHookUpdate description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * The description of the object.
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public WebHookUpdate customProperties(@javax.annotation.Nullable Map<String, String> customProperties) {
    this.customProperties = customProperties;
    return this;
  }

  public WebHookUpdate putCustomPropertiesItem(String key, String customPropertiesItem) {
    if (this.customProperties == null) {
      this.customProperties = new HashMap<>();
    }
    this.customProperties.put(key, customPropertiesItem);
    return this;
  }

  /**
   * The custom properties of this entity. The maximum allowed key length is 64 characters, the maximum  allowed value length is 256 characters and the count of allowed entries is 10.
   * @return customProperties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getCustomProperties() {
    return customProperties;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomProperties(@javax.annotation.Nullable Map<String, String> customProperties) {
    this.customProperties = customProperties;
  }


  /**
   * Return true if this WebHookUpdate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebHookUpdate webHookUpdate = (WebHookUpdate) o;
    return Objects.equals(this.webUrl, webHookUpdate.webUrl) &&
        Objects.equals(this.properties, webHookUpdate.properties) &&
        Objects.equals(this.events, webHookUpdate.events) &&
        Objects.equals(this.displayName, webHookUpdate.displayName) &&
        Objects.equals(this.description, webHookUpdate.description) &&
        Objects.equals(this.customProperties, webHookUpdate.customProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(webUrl, properties, events, displayName, description, customProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebHookUpdate {\n");
    sb.append("    webUrl: ").append(toIndentedString(webUrl)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    customProperties: ").append(toIndentedString(customProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `webUrl` to the URL query string
    if (getWebUrl() != null) {
      joiner.add(String.format("%swebUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebUrl()))));
    }

    // add `properties` to the URL query string
    if (getProperties() != null) {
      joiner.add(getProperties().toUrlQueryString(prefix + "properties" + suffix));
    }

    // add `events` to the URL query string
    if (getEvents() != null) {
      joiner.add(getEvents().toUrlQueryString(prefix + "events" + suffix));
    }

    // add `displayName` to the URL query string
    if (getDisplayName() != null) {
      joiner.add(String.format("%sdisplayName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisplayName()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `customProperties` to the URL query string
    if (getCustomProperties() != null) {
      for (String _key : getCustomProperties().keySet()) {
        joiner.add(String.format("%scustomProperties%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getCustomProperties().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getCustomProperties().get(_key)))));
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private WebHookUpdate instance;

    public Builder() {
      this(new WebHookUpdate());
    }

    protected Builder(WebHookUpdate instance) {
      this.instance = instance;
    }

    public WebHookUpdate.Builder webUrl(URI webUrl) {
      this.instance.webUrl = webUrl;
      return this;
    }
    public WebHookUpdate.Builder properties(WebHookPropertiesUpdate properties) {
      this.instance.properties = properties;
      return this;
    }
    public WebHookUpdate.Builder events(WebHookEvents events) {
      this.instance.events = events;
      return this;
    }
    public WebHookUpdate.Builder displayName(String displayName) {
      this.instance.displayName = displayName;
      return this;
    }
    public WebHookUpdate.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public WebHookUpdate.Builder customProperties(Map<String, String> customProperties) {
      this.instance.customProperties = customProperties;
      return this;
    }


    /**
    * returns a built WebHookUpdate instance.
    *
    * The builder is not reusable.
    */
    public WebHookUpdate build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static WebHookUpdate.Builder builder() {
    return new WebHookUpdate.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public WebHookUpdate.Builder toBuilder() {
    return new WebHookUpdate.Builder()
      .webUrl(getWebUrl())
      .properties(getProperties())
      .events(getEvents())
      .displayName(getDisplayName())
      .description(getDescription())
      .customProperties(getCustomProperties());
  }

}

