/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * WebHookEvents
 */
@JsonPropertyOrder({
  WebHookEvents.JSON_PROPERTY_DATASET_CREATION,
  WebHookEvents.JSON_PROPERTY_DATASET_PROCESSING,
  WebHookEvents.JSON_PROPERTY_DATASET_COMPLETION,
  WebHookEvents.JSON_PROPERTY_DATASET_DELETION,
  WebHookEvents.JSON_PROPERTY_MODEL_CREATION,
  WebHookEvents.JSON_PROPERTY_MODEL_PROCESSING,
  WebHookEvents.JSON_PROPERTY_MODEL_COMPLETION,
  WebHookEvents.JSON_PROPERTY_MODEL_DELETION,
  WebHookEvents.JSON_PROPERTY_EVALUATION_CREATION,
  WebHookEvents.JSON_PROPERTY_EVALUATION_PROCESSING,
  WebHookEvents.JSON_PROPERTY_EVALUATION_COMPLETION,
  WebHookEvents.JSON_PROPERTY_EVALUATION_DELETION,
  WebHookEvents.JSON_PROPERTY_TRANSCRIPTION_CREATION,
  WebHookEvents.JSON_PROPERTY_TRANSCRIPTION_PROCESSING,
  WebHookEvents.JSON_PROPERTY_TRANSCRIPTION_COMPLETION,
  WebHookEvents.JSON_PROPERTY_TRANSCRIPTION_DELETION,
  WebHookEvents.JSON_PROPERTY_ENDPOINT_CREATION,
  WebHookEvents.JSON_PROPERTY_ENDPOINT_PROCESSING,
  WebHookEvents.JSON_PROPERTY_ENDPOINT_COMPLETION,
  WebHookEvents.JSON_PROPERTY_ENDPOINT_DELETION,
  WebHookEvents.JSON_PROPERTY_PING,
  WebHookEvents.JSON_PROPERTY_CHALLENGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T10:07:46.057250+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class WebHookEvents {
  public static final String JSON_PROPERTY_DATASET_CREATION = "datasetCreation";
  @javax.annotation.Nullable
  private Boolean datasetCreation;

  public static final String JSON_PROPERTY_DATASET_PROCESSING = "datasetProcessing";
  @javax.annotation.Nullable
  private Boolean datasetProcessing;

  public static final String JSON_PROPERTY_DATASET_COMPLETION = "datasetCompletion";
  @javax.annotation.Nullable
  private Boolean datasetCompletion;

  public static final String JSON_PROPERTY_DATASET_DELETION = "datasetDeletion";
  @javax.annotation.Nullable
  private Boolean datasetDeletion;

  public static final String JSON_PROPERTY_MODEL_CREATION = "modelCreation";
  @javax.annotation.Nullable
  private Boolean modelCreation;

  public static final String JSON_PROPERTY_MODEL_PROCESSING = "modelProcessing";
  @javax.annotation.Nullable
  private Boolean modelProcessing;

  public static final String JSON_PROPERTY_MODEL_COMPLETION = "modelCompletion";
  @javax.annotation.Nullable
  private Boolean modelCompletion;

  public static final String JSON_PROPERTY_MODEL_DELETION = "modelDeletion";
  @javax.annotation.Nullable
  private Boolean modelDeletion;

  public static final String JSON_PROPERTY_EVALUATION_CREATION = "evaluationCreation";
  @javax.annotation.Nullable
  private Boolean evaluationCreation;

  public static final String JSON_PROPERTY_EVALUATION_PROCESSING = "evaluationProcessing";
  @javax.annotation.Nullable
  private Boolean evaluationProcessing;

  public static final String JSON_PROPERTY_EVALUATION_COMPLETION = "evaluationCompletion";
  @javax.annotation.Nullable
  private Boolean evaluationCompletion;

  public static final String JSON_PROPERTY_EVALUATION_DELETION = "evaluationDeletion";
  @javax.annotation.Nullable
  private Boolean evaluationDeletion;

  public static final String JSON_PROPERTY_TRANSCRIPTION_CREATION = "transcriptionCreation";
  @javax.annotation.Nullable
  private Boolean transcriptionCreation;

  public static final String JSON_PROPERTY_TRANSCRIPTION_PROCESSING = "transcriptionProcessing";
  @javax.annotation.Nullable
  private Boolean transcriptionProcessing;

  public static final String JSON_PROPERTY_TRANSCRIPTION_COMPLETION = "transcriptionCompletion";
  @javax.annotation.Nullable
  private Boolean transcriptionCompletion;

  public static final String JSON_PROPERTY_TRANSCRIPTION_DELETION = "transcriptionDeletion";
  @javax.annotation.Nullable
  private Boolean transcriptionDeletion;

  public static final String JSON_PROPERTY_ENDPOINT_CREATION = "endpointCreation";
  @javax.annotation.Nullable
  private Boolean endpointCreation;

  public static final String JSON_PROPERTY_ENDPOINT_PROCESSING = "endpointProcessing";
  @javax.annotation.Nullable
  private Boolean endpointProcessing;

  public static final String JSON_PROPERTY_ENDPOINT_COMPLETION = "endpointCompletion";
  @javax.annotation.Nullable
  private Boolean endpointCompletion;

  public static final String JSON_PROPERTY_ENDPOINT_DELETION = "endpointDeletion";
  @javax.annotation.Nullable
  private Boolean endpointDeletion;

  public static final String JSON_PROPERTY_PING = "ping";
  @javax.annotation.Nullable
  private Boolean ping;

  public static final String JSON_PROPERTY_CHALLENGE = "challenge";
  @javax.annotation.Nullable
  private Boolean challenge;

  public WebHookEvents() { 
  }

  public WebHookEvents datasetCreation(@javax.annotation.Nullable Boolean datasetCreation) {
    this.datasetCreation = datasetCreation;
    return this;
  }

  /**
   * Get datasetCreation
   * @return datasetCreation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATASET_CREATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDatasetCreation() {
    return datasetCreation;
  }


  @JsonProperty(JSON_PROPERTY_DATASET_CREATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatasetCreation(@javax.annotation.Nullable Boolean datasetCreation) {
    this.datasetCreation = datasetCreation;
  }


  public WebHookEvents datasetProcessing(@javax.annotation.Nullable Boolean datasetProcessing) {
    this.datasetProcessing = datasetProcessing;
    return this;
  }

  /**
   * Get datasetProcessing
   * @return datasetProcessing
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATASET_PROCESSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDatasetProcessing() {
    return datasetProcessing;
  }


  @JsonProperty(JSON_PROPERTY_DATASET_PROCESSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatasetProcessing(@javax.annotation.Nullable Boolean datasetProcessing) {
    this.datasetProcessing = datasetProcessing;
  }


  public WebHookEvents datasetCompletion(@javax.annotation.Nullable Boolean datasetCompletion) {
    this.datasetCompletion = datasetCompletion;
    return this;
  }

  /**
   * Get datasetCompletion
   * @return datasetCompletion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATASET_COMPLETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDatasetCompletion() {
    return datasetCompletion;
  }


  @JsonProperty(JSON_PROPERTY_DATASET_COMPLETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatasetCompletion(@javax.annotation.Nullable Boolean datasetCompletion) {
    this.datasetCompletion = datasetCompletion;
  }


  public WebHookEvents datasetDeletion(@javax.annotation.Nullable Boolean datasetDeletion) {
    this.datasetDeletion = datasetDeletion;
    return this;
  }

  /**
   * Get datasetDeletion
   * @return datasetDeletion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATASET_DELETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDatasetDeletion() {
    return datasetDeletion;
  }


  @JsonProperty(JSON_PROPERTY_DATASET_DELETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatasetDeletion(@javax.annotation.Nullable Boolean datasetDeletion) {
    this.datasetDeletion = datasetDeletion;
  }


  public WebHookEvents modelCreation(@javax.annotation.Nullable Boolean modelCreation) {
    this.modelCreation = modelCreation;
    return this;
  }

  /**
   * Get modelCreation
   * @return modelCreation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL_CREATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getModelCreation() {
    return modelCreation;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_CREATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModelCreation(@javax.annotation.Nullable Boolean modelCreation) {
    this.modelCreation = modelCreation;
  }


  public WebHookEvents modelProcessing(@javax.annotation.Nullable Boolean modelProcessing) {
    this.modelProcessing = modelProcessing;
    return this;
  }

  /**
   * Get modelProcessing
   * @return modelProcessing
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL_PROCESSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getModelProcessing() {
    return modelProcessing;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_PROCESSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModelProcessing(@javax.annotation.Nullable Boolean modelProcessing) {
    this.modelProcessing = modelProcessing;
  }


  public WebHookEvents modelCompletion(@javax.annotation.Nullable Boolean modelCompletion) {
    this.modelCompletion = modelCompletion;
    return this;
  }

  /**
   * Get modelCompletion
   * @return modelCompletion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL_COMPLETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getModelCompletion() {
    return modelCompletion;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_COMPLETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModelCompletion(@javax.annotation.Nullable Boolean modelCompletion) {
    this.modelCompletion = modelCompletion;
  }


  public WebHookEvents modelDeletion(@javax.annotation.Nullable Boolean modelDeletion) {
    this.modelDeletion = modelDeletion;
    return this;
  }

  /**
   * Get modelDeletion
   * @return modelDeletion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL_DELETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getModelDeletion() {
    return modelDeletion;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_DELETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModelDeletion(@javax.annotation.Nullable Boolean modelDeletion) {
    this.modelDeletion = modelDeletion;
  }


  public WebHookEvents evaluationCreation(@javax.annotation.Nullable Boolean evaluationCreation) {
    this.evaluationCreation = evaluationCreation;
    return this;
  }

  /**
   * Get evaluationCreation
   * @return evaluationCreation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVALUATION_CREATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEvaluationCreation() {
    return evaluationCreation;
  }


  @JsonProperty(JSON_PROPERTY_EVALUATION_CREATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvaluationCreation(@javax.annotation.Nullable Boolean evaluationCreation) {
    this.evaluationCreation = evaluationCreation;
  }


  public WebHookEvents evaluationProcessing(@javax.annotation.Nullable Boolean evaluationProcessing) {
    this.evaluationProcessing = evaluationProcessing;
    return this;
  }

  /**
   * Get evaluationProcessing
   * @return evaluationProcessing
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVALUATION_PROCESSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEvaluationProcessing() {
    return evaluationProcessing;
  }


  @JsonProperty(JSON_PROPERTY_EVALUATION_PROCESSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvaluationProcessing(@javax.annotation.Nullable Boolean evaluationProcessing) {
    this.evaluationProcessing = evaluationProcessing;
  }


  public WebHookEvents evaluationCompletion(@javax.annotation.Nullable Boolean evaluationCompletion) {
    this.evaluationCompletion = evaluationCompletion;
    return this;
  }

  /**
   * Get evaluationCompletion
   * @return evaluationCompletion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVALUATION_COMPLETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEvaluationCompletion() {
    return evaluationCompletion;
  }


  @JsonProperty(JSON_PROPERTY_EVALUATION_COMPLETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvaluationCompletion(@javax.annotation.Nullable Boolean evaluationCompletion) {
    this.evaluationCompletion = evaluationCompletion;
  }


  public WebHookEvents evaluationDeletion(@javax.annotation.Nullable Boolean evaluationDeletion) {
    this.evaluationDeletion = evaluationDeletion;
    return this;
  }

  /**
   * Get evaluationDeletion
   * @return evaluationDeletion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVALUATION_DELETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEvaluationDeletion() {
    return evaluationDeletion;
  }


  @JsonProperty(JSON_PROPERTY_EVALUATION_DELETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvaluationDeletion(@javax.annotation.Nullable Boolean evaluationDeletion) {
    this.evaluationDeletion = evaluationDeletion;
  }


  public WebHookEvents transcriptionCreation(@javax.annotation.Nullable Boolean transcriptionCreation) {
    this.transcriptionCreation = transcriptionCreation;
    return this;
  }

  /**
   * Get transcriptionCreation
   * @return transcriptionCreation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSCRIPTION_CREATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getTranscriptionCreation() {
    return transcriptionCreation;
  }


  @JsonProperty(JSON_PROPERTY_TRANSCRIPTION_CREATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTranscriptionCreation(@javax.annotation.Nullable Boolean transcriptionCreation) {
    this.transcriptionCreation = transcriptionCreation;
  }


  public WebHookEvents transcriptionProcessing(@javax.annotation.Nullable Boolean transcriptionProcessing) {
    this.transcriptionProcessing = transcriptionProcessing;
    return this;
  }

  /**
   * Get transcriptionProcessing
   * @return transcriptionProcessing
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSCRIPTION_PROCESSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getTranscriptionProcessing() {
    return transcriptionProcessing;
  }


  @JsonProperty(JSON_PROPERTY_TRANSCRIPTION_PROCESSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTranscriptionProcessing(@javax.annotation.Nullable Boolean transcriptionProcessing) {
    this.transcriptionProcessing = transcriptionProcessing;
  }


  public WebHookEvents transcriptionCompletion(@javax.annotation.Nullable Boolean transcriptionCompletion) {
    this.transcriptionCompletion = transcriptionCompletion;
    return this;
  }

  /**
   * Get transcriptionCompletion
   * @return transcriptionCompletion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSCRIPTION_COMPLETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getTranscriptionCompletion() {
    return transcriptionCompletion;
  }


  @JsonProperty(JSON_PROPERTY_TRANSCRIPTION_COMPLETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTranscriptionCompletion(@javax.annotation.Nullable Boolean transcriptionCompletion) {
    this.transcriptionCompletion = transcriptionCompletion;
  }


  public WebHookEvents transcriptionDeletion(@javax.annotation.Nullable Boolean transcriptionDeletion) {
    this.transcriptionDeletion = transcriptionDeletion;
    return this;
  }

  /**
   * Get transcriptionDeletion
   * @return transcriptionDeletion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSCRIPTION_DELETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getTranscriptionDeletion() {
    return transcriptionDeletion;
  }


  @JsonProperty(JSON_PROPERTY_TRANSCRIPTION_DELETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTranscriptionDeletion(@javax.annotation.Nullable Boolean transcriptionDeletion) {
    this.transcriptionDeletion = transcriptionDeletion;
  }


  public WebHookEvents endpointCreation(@javax.annotation.Nullable Boolean endpointCreation) {
    this.endpointCreation = endpointCreation;
    return this;
  }

  /**
   * Get endpointCreation
   * @return endpointCreation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENDPOINT_CREATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEndpointCreation() {
    return endpointCreation;
  }


  @JsonProperty(JSON_PROPERTY_ENDPOINT_CREATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointCreation(@javax.annotation.Nullable Boolean endpointCreation) {
    this.endpointCreation = endpointCreation;
  }


  public WebHookEvents endpointProcessing(@javax.annotation.Nullable Boolean endpointProcessing) {
    this.endpointProcessing = endpointProcessing;
    return this;
  }

  /**
   * Get endpointProcessing
   * @return endpointProcessing
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENDPOINT_PROCESSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEndpointProcessing() {
    return endpointProcessing;
  }


  @JsonProperty(JSON_PROPERTY_ENDPOINT_PROCESSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointProcessing(@javax.annotation.Nullable Boolean endpointProcessing) {
    this.endpointProcessing = endpointProcessing;
  }


  public WebHookEvents endpointCompletion(@javax.annotation.Nullable Boolean endpointCompletion) {
    this.endpointCompletion = endpointCompletion;
    return this;
  }

  /**
   * Get endpointCompletion
   * @return endpointCompletion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENDPOINT_COMPLETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEndpointCompletion() {
    return endpointCompletion;
  }


  @JsonProperty(JSON_PROPERTY_ENDPOINT_COMPLETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointCompletion(@javax.annotation.Nullable Boolean endpointCompletion) {
    this.endpointCompletion = endpointCompletion;
  }


  public WebHookEvents endpointDeletion(@javax.annotation.Nullable Boolean endpointDeletion) {
    this.endpointDeletion = endpointDeletion;
    return this;
  }

  /**
   * Get endpointDeletion
   * @return endpointDeletion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENDPOINT_DELETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEndpointDeletion() {
    return endpointDeletion;
  }


  @JsonProperty(JSON_PROPERTY_ENDPOINT_DELETION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointDeletion(@javax.annotation.Nullable Boolean endpointDeletion) {
    this.endpointDeletion = endpointDeletion;
  }


  public WebHookEvents ping(@javax.annotation.Nullable Boolean ping) {
    this.ping = ping;
    return this;
  }

  /**
   * Get ping
   * @return ping
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getPing() {
    return ping;
  }


  @JsonProperty(JSON_PROPERTY_PING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPing(@javax.annotation.Nullable Boolean ping) {
    this.ping = ping;
  }


  public WebHookEvents challenge(@javax.annotation.Nullable Boolean challenge) {
    this.challenge = challenge;
    return this;
  }

  /**
   * Get challenge
   * @return challenge
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getChallenge() {
    return challenge;
  }


  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChallenge(@javax.annotation.Nullable Boolean challenge) {
    this.challenge = challenge;
  }


  /**
   * Return true if this WebHookEvents object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebHookEvents webHookEvents = (WebHookEvents) o;
    return Objects.equals(this.datasetCreation, webHookEvents.datasetCreation) &&
        Objects.equals(this.datasetProcessing, webHookEvents.datasetProcessing) &&
        Objects.equals(this.datasetCompletion, webHookEvents.datasetCompletion) &&
        Objects.equals(this.datasetDeletion, webHookEvents.datasetDeletion) &&
        Objects.equals(this.modelCreation, webHookEvents.modelCreation) &&
        Objects.equals(this.modelProcessing, webHookEvents.modelProcessing) &&
        Objects.equals(this.modelCompletion, webHookEvents.modelCompletion) &&
        Objects.equals(this.modelDeletion, webHookEvents.modelDeletion) &&
        Objects.equals(this.evaluationCreation, webHookEvents.evaluationCreation) &&
        Objects.equals(this.evaluationProcessing, webHookEvents.evaluationProcessing) &&
        Objects.equals(this.evaluationCompletion, webHookEvents.evaluationCompletion) &&
        Objects.equals(this.evaluationDeletion, webHookEvents.evaluationDeletion) &&
        Objects.equals(this.transcriptionCreation, webHookEvents.transcriptionCreation) &&
        Objects.equals(this.transcriptionProcessing, webHookEvents.transcriptionProcessing) &&
        Objects.equals(this.transcriptionCompletion, webHookEvents.transcriptionCompletion) &&
        Objects.equals(this.transcriptionDeletion, webHookEvents.transcriptionDeletion) &&
        Objects.equals(this.endpointCreation, webHookEvents.endpointCreation) &&
        Objects.equals(this.endpointProcessing, webHookEvents.endpointProcessing) &&
        Objects.equals(this.endpointCompletion, webHookEvents.endpointCompletion) &&
        Objects.equals(this.endpointDeletion, webHookEvents.endpointDeletion) &&
        Objects.equals(this.ping, webHookEvents.ping) &&
        Objects.equals(this.challenge, webHookEvents.challenge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datasetCreation, datasetProcessing, datasetCompletion, datasetDeletion, modelCreation, modelProcessing, modelCompletion, modelDeletion, evaluationCreation, evaluationProcessing, evaluationCompletion, evaluationDeletion, transcriptionCreation, transcriptionProcessing, transcriptionCompletion, transcriptionDeletion, endpointCreation, endpointProcessing, endpointCompletion, endpointDeletion, ping, challenge);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebHookEvents {\n");
    sb.append("    datasetCreation: ").append(toIndentedString(datasetCreation)).append("\n");
    sb.append("    datasetProcessing: ").append(toIndentedString(datasetProcessing)).append("\n");
    sb.append("    datasetCompletion: ").append(toIndentedString(datasetCompletion)).append("\n");
    sb.append("    datasetDeletion: ").append(toIndentedString(datasetDeletion)).append("\n");
    sb.append("    modelCreation: ").append(toIndentedString(modelCreation)).append("\n");
    sb.append("    modelProcessing: ").append(toIndentedString(modelProcessing)).append("\n");
    sb.append("    modelCompletion: ").append(toIndentedString(modelCompletion)).append("\n");
    sb.append("    modelDeletion: ").append(toIndentedString(modelDeletion)).append("\n");
    sb.append("    evaluationCreation: ").append(toIndentedString(evaluationCreation)).append("\n");
    sb.append("    evaluationProcessing: ").append(toIndentedString(evaluationProcessing)).append("\n");
    sb.append("    evaluationCompletion: ").append(toIndentedString(evaluationCompletion)).append("\n");
    sb.append("    evaluationDeletion: ").append(toIndentedString(evaluationDeletion)).append("\n");
    sb.append("    transcriptionCreation: ").append(toIndentedString(transcriptionCreation)).append("\n");
    sb.append("    transcriptionProcessing: ").append(toIndentedString(transcriptionProcessing)).append("\n");
    sb.append("    transcriptionCompletion: ").append(toIndentedString(transcriptionCompletion)).append("\n");
    sb.append("    transcriptionDeletion: ").append(toIndentedString(transcriptionDeletion)).append("\n");
    sb.append("    endpointCreation: ").append(toIndentedString(endpointCreation)).append("\n");
    sb.append("    endpointProcessing: ").append(toIndentedString(endpointProcessing)).append("\n");
    sb.append("    endpointCompletion: ").append(toIndentedString(endpointCompletion)).append("\n");
    sb.append("    endpointDeletion: ").append(toIndentedString(endpointDeletion)).append("\n");
    sb.append("    ping: ").append(toIndentedString(ping)).append("\n");
    sb.append("    challenge: ").append(toIndentedString(challenge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `datasetCreation` to the URL query string
    if (getDatasetCreation() != null) {
      joiner.add(String.format("%sdatasetCreation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDatasetCreation()))));
    }

    // add `datasetProcessing` to the URL query string
    if (getDatasetProcessing() != null) {
      joiner.add(String.format("%sdatasetProcessing%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDatasetProcessing()))));
    }

    // add `datasetCompletion` to the URL query string
    if (getDatasetCompletion() != null) {
      joiner.add(String.format("%sdatasetCompletion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDatasetCompletion()))));
    }

    // add `datasetDeletion` to the URL query string
    if (getDatasetDeletion() != null) {
      joiner.add(String.format("%sdatasetDeletion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDatasetDeletion()))));
    }

    // add `modelCreation` to the URL query string
    if (getModelCreation() != null) {
      joiner.add(String.format("%smodelCreation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModelCreation()))));
    }

    // add `modelProcessing` to the URL query string
    if (getModelProcessing() != null) {
      joiner.add(String.format("%smodelProcessing%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModelProcessing()))));
    }

    // add `modelCompletion` to the URL query string
    if (getModelCompletion() != null) {
      joiner.add(String.format("%smodelCompletion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModelCompletion()))));
    }

    // add `modelDeletion` to the URL query string
    if (getModelDeletion() != null) {
      joiner.add(String.format("%smodelDeletion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModelDeletion()))));
    }

    // add `evaluationCreation` to the URL query string
    if (getEvaluationCreation() != null) {
      joiner.add(String.format("%sevaluationCreation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEvaluationCreation()))));
    }

    // add `evaluationProcessing` to the URL query string
    if (getEvaluationProcessing() != null) {
      joiner.add(String.format("%sevaluationProcessing%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEvaluationProcessing()))));
    }

    // add `evaluationCompletion` to the URL query string
    if (getEvaluationCompletion() != null) {
      joiner.add(String.format("%sevaluationCompletion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEvaluationCompletion()))));
    }

    // add `evaluationDeletion` to the URL query string
    if (getEvaluationDeletion() != null) {
      joiner.add(String.format("%sevaluationDeletion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEvaluationDeletion()))));
    }

    // add `transcriptionCreation` to the URL query string
    if (getTranscriptionCreation() != null) {
      joiner.add(String.format("%stranscriptionCreation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTranscriptionCreation()))));
    }

    // add `transcriptionProcessing` to the URL query string
    if (getTranscriptionProcessing() != null) {
      joiner.add(String.format("%stranscriptionProcessing%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTranscriptionProcessing()))));
    }

    // add `transcriptionCompletion` to the URL query string
    if (getTranscriptionCompletion() != null) {
      joiner.add(String.format("%stranscriptionCompletion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTranscriptionCompletion()))));
    }

    // add `transcriptionDeletion` to the URL query string
    if (getTranscriptionDeletion() != null) {
      joiner.add(String.format("%stranscriptionDeletion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTranscriptionDeletion()))));
    }

    // add `endpointCreation` to the URL query string
    if (getEndpointCreation() != null) {
      joiner.add(String.format("%sendpointCreation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointCreation()))));
    }

    // add `endpointProcessing` to the URL query string
    if (getEndpointProcessing() != null) {
      joiner.add(String.format("%sendpointProcessing%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointProcessing()))));
    }

    // add `endpointCompletion` to the URL query string
    if (getEndpointCompletion() != null) {
      joiner.add(String.format("%sendpointCompletion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointCompletion()))));
    }

    // add `endpointDeletion` to the URL query string
    if (getEndpointDeletion() != null) {
      joiner.add(String.format("%sendpointDeletion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointDeletion()))));
    }

    // add `ping` to the URL query string
    if (getPing() != null) {
      joiner.add(String.format("%sping%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPing()))));
    }

    // add `challenge` to the URL query string
    if (getChallenge() != null) {
      joiner.add(String.format("%schallenge%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChallenge()))));
    }

    return joiner.toString();
  }

    public static class Builder {

    private WebHookEvents instance;

    public Builder() {
      this(new WebHookEvents());
    }

    protected Builder(WebHookEvents instance) {
      this.instance = instance;
    }

    public WebHookEvents.Builder datasetCreation(Boolean datasetCreation) {
      this.instance.datasetCreation = datasetCreation;
      return this;
    }
    public WebHookEvents.Builder datasetProcessing(Boolean datasetProcessing) {
      this.instance.datasetProcessing = datasetProcessing;
      return this;
    }
    public WebHookEvents.Builder datasetCompletion(Boolean datasetCompletion) {
      this.instance.datasetCompletion = datasetCompletion;
      return this;
    }
    public WebHookEvents.Builder datasetDeletion(Boolean datasetDeletion) {
      this.instance.datasetDeletion = datasetDeletion;
      return this;
    }
    public WebHookEvents.Builder modelCreation(Boolean modelCreation) {
      this.instance.modelCreation = modelCreation;
      return this;
    }
    public WebHookEvents.Builder modelProcessing(Boolean modelProcessing) {
      this.instance.modelProcessing = modelProcessing;
      return this;
    }
    public WebHookEvents.Builder modelCompletion(Boolean modelCompletion) {
      this.instance.modelCompletion = modelCompletion;
      return this;
    }
    public WebHookEvents.Builder modelDeletion(Boolean modelDeletion) {
      this.instance.modelDeletion = modelDeletion;
      return this;
    }
    public WebHookEvents.Builder evaluationCreation(Boolean evaluationCreation) {
      this.instance.evaluationCreation = evaluationCreation;
      return this;
    }
    public WebHookEvents.Builder evaluationProcessing(Boolean evaluationProcessing) {
      this.instance.evaluationProcessing = evaluationProcessing;
      return this;
    }
    public WebHookEvents.Builder evaluationCompletion(Boolean evaluationCompletion) {
      this.instance.evaluationCompletion = evaluationCompletion;
      return this;
    }
    public WebHookEvents.Builder evaluationDeletion(Boolean evaluationDeletion) {
      this.instance.evaluationDeletion = evaluationDeletion;
      return this;
    }
    public WebHookEvents.Builder transcriptionCreation(Boolean transcriptionCreation) {
      this.instance.transcriptionCreation = transcriptionCreation;
      return this;
    }
    public WebHookEvents.Builder transcriptionProcessing(Boolean transcriptionProcessing) {
      this.instance.transcriptionProcessing = transcriptionProcessing;
      return this;
    }
    public WebHookEvents.Builder transcriptionCompletion(Boolean transcriptionCompletion) {
      this.instance.transcriptionCompletion = transcriptionCompletion;
      return this;
    }
    public WebHookEvents.Builder transcriptionDeletion(Boolean transcriptionDeletion) {
      this.instance.transcriptionDeletion = transcriptionDeletion;
      return this;
    }
    public WebHookEvents.Builder endpointCreation(Boolean endpointCreation) {
      this.instance.endpointCreation = endpointCreation;
      return this;
    }
    public WebHookEvents.Builder endpointProcessing(Boolean endpointProcessing) {
      this.instance.endpointProcessing = endpointProcessing;
      return this;
    }
    public WebHookEvents.Builder endpointCompletion(Boolean endpointCompletion) {
      this.instance.endpointCompletion = endpointCompletion;
      return this;
    }
    public WebHookEvents.Builder endpointDeletion(Boolean endpointDeletion) {
      this.instance.endpointDeletion = endpointDeletion;
      return this;
    }
    public WebHookEvents.Builder ping(Boolean ping) {
      this.instance.ping = ping;
      return this;
    }
    public WebHookEvents.Builder challenge(Boolean challenge) {
      this.instance.challenge = challenge;
      return this;
    }


    /**
    * returns a built WebHookEvents instance.
    *
    * The builder is not reusable.
    */
    public WebHookEvents build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static WebHookEvents.Builder builder() {
    return new WebHookEvents.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public WebHookEvents.Builder toBuilder() {
    return new WebHookEvents.Builder()
      .datasetCreation(getDatasetCreation())
      .datasetProcessing(getDatasetProcessing())
      .datasetCompletion(getDatasetCompletion())
      .datasetDeletion(getDatasetDeletion())
      .modelCreation(getModelCreation())
      .modelProcessing(getModelProcessing())
      .modelCompletion(getModelCompletion())
      .modelDeletion(getModelDeletion())
      .evaluationCreation(getEvaluationCreation())
      .evaluationProcessing(getEvaluationProcessing())
      .evaluationCompletion(getEvaluationCompletion())
      .evaluationDeletion(getEvaluationDeletion())
      .transcriptionCreation(getTranscriptionCreation())
      .transcriptionProcessing(getTranscriptionProcessing())
      .transcriptionCompletion(getTranscriptionCompletion())
      .transcriptionDeletion(getTranscriptionDeletion())
      .endpointCreation(getEndpointCreation())
      .endpointProcessing(getEndpointProcessing())
      .endpointCompletion(getEndpointCompletion())
      .endpointDeletion(getEndpointDeletion())
      .ping(getPing())
      .challenge(getChallenge());
  }

}

