/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Operation;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomSpeechOperationsApi
 */
@Disabled
public class CustomSpeechOperationsApiTest {

    private final CustomSpeechOperationsApi api = new CustomSpeechOperationsApi();

    /**
     * Gets the operation identified by the given ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void operationsGetModelCopyTest() throws ApiException {
        UUID id = null;
        Operation response = api.operationsGetModelCopy(id);
        // TODO: test validations
    }

}
