/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.BaseModelDeprecationDates;
import org.openapitools.client.model.BaseModelFeatures;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BaseModelProperties
 */
public class BaseModelPropertiesTest {
    private final BaseModelProperties model = new BaseModelProperties();

    /**
     * Model tests for BaseModelProperties
     */
    @Test
    public void testBaseModelProperties() {
        // TODO: test BaseModelProperties
    }

    /**
     * Test the property 'deprecationDates'
     */
    @Test
    public void deprecationDatesTest() {
        // TODO: test deprecationDates
    }

    /**
     * Test the property 'features'
     */
    @Test
    public void featuresTest() {
        // TODO: test features
    }

    /**
     * Test the property 'chargeForAdaptation'
     */
    @Test
    public void chargeForAdaptationTest() {
        // TODO: test chargeForAdaptation
    }

}
