/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LanguageIdentificationMode
 */
public class LanguageIdentificationModeTest {
    /**
     * Model tests for LanguageIdentificationMode
     */
    @Test
    public void testLanguageIdentificationMode() {
        // TODO: test LanguageIdentificationMode
    }

}
