/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ModelCopyAuthorization
 */
public class ModelCopyAuthorizationTest {
    private final ModelCopyAuthorization model = new ModelCopyAuthorization();

    /**
     * Model tests for ModelCopyAuthorization
     */
    @Test
    public void testModelCopyAuthorization() {
        // TODO: test ModelCopyAuthorization
    }

    /**
     * Test the property 'targetResourceRegion'
     */
    @Test
    public void targetResourceRegionTest() {
        // TODO: test targetResourceRegion
    }

    /**
     * Test the property 'targetResourceId'
     */
    @Test
    public void targetResourceIdTest() {
        // TODO: test targetResourceId
    }

    /**
     * Test the property 'targetResourceEndpoint'
     */
    @Test
    public void targetResourceEndpointTest() {
        // TODO: test targetResourceEndpoint
    }

    /**
     * Test the property 'sourceResourceId'
     */
    @Test
    public void sourceResourceIdTest() {
        // TODO: test sourceResourceId
    }

    /**
     * Test the property 'expirationDateTime'
     */
    @Test
    public void expirationDateTimeTest() {
        // TODO: test expirationDateTime
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
