/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ModelCopyAuthorizationDefinition
 */
public class ModelCopyAuthorizationDefinitionTest {
    private final ModelCopyAuthorizationDefinition model = new ModelCopyAuthorizationDefinition();

    /**
     * Model tests for ModelCopyAuthorizationDefinition
     */
    @Test
    public void testModelCopyAuthorizationDefinition() {
        // TODO: test ModelCopyAuthorizationDefinition
    }

    /**
     * Test the property 'sourceResourceId'
     */
    @Test
    public void sourceResourceIdTest() {
        // TODO: test sourceResourceId
    }

}
