/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectProperties
 */
public class ProjectPropertiesTest {
    private final ProjectProperties model = new ProjectProperties();

    /**
     * Model tests for ProjectProperties
     */
    @Test
    public void testProjectProperties() {
        // TODO: test ProjectProperties
    }

    /**
     * Test the property 'datasetCount'
     */
    @Test
    public void datasetCountTest() {
        // TODO: test datasetCount
    }

    /**
     * Test the property 'evaluationCount'
     */
    @Test
    public void evaluationCountTest() {
        // TODO: test evaluationCount
    }

    /**
     * Test the property 'modelCount'
     */
    @Test
    public void modelCountTest() {
        // TODO: test modelCount
    }

    /**
     * Test the property 'transcriptionCount'
     */
    @Test
    public void transcriptionCountTest() {
        // TODO: test transcriptionCount
    }

    /**
     * Test the property 'endpointCount'
     */
    @Test
    public void endpointCountTest() {
        // TODO: test endpointCount
    }

}
