/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.OutputFormatType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SharedModelFeatures
 */
public class SharedModelFeaturesTest {
    private final SharedModelFeatures model = new SharedModelFeatures();

    /**
     * Model tests for SharedModelFeatures
     */
    @Test
    public void testSharedModelFeatures() {
        // TODO: test SharedModelFeatures
    }

    /**
     * Test the property 'supportsTranscriptions'
     */
    @Test
    public void supportsTranscriptionsTest() {
        // TODO: test supportsTranscriptions
    }

    /**
     * Test the property 'supportsEndpoints'
     */
    @Test
    public void supportsEndpointsTest() {
        // TODO: test supportsEndpoints
    }

    /**
     * Test the property 'supportsTranscriptionsOnSpeechContainers'
     */
    @Test
    public void supportsTranscriptionsOnSpeechContainersTest() {
        // TODO: test supportsTranscriptionsOnSpeechContainers
    }

    /**
     * Test the property 'supportedOutputFormats'
     */
    @Test
    public void supportedOutputFormatsTest() {
        // TODO: test supportedOutputFormats
    }

}
