/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ResponseBlock;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UploadedBlocks
 */
public class UploadedBlocksTest {
    private final UploadedBlocks model = new UploadedBlocks();

    /**
     * Model tests for UploadedBlocks
     */
    @Test
    public void testUploadedBlocks() {
        // TODO: test UploadedBlocks
    }

    /**
     * Test the property 'committedBlocks'
     */
    @Test
    public void committedBlocksTest() {
        // TODO: test committedBlocks
    }

    /**
     * Test the property 'uncommittedBlocks'
     */
    @Test
    public void uncommittedBlocksTest() {
        // TODO: test uncommittedBlocks
    }

}
