/*
 * Speech Services API version 3.2
 * Speech Services API version 3.2.
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebHookEvents
 */
public class WebHookEventsTest {
    private final WebHookEvents model = new WebHookEvents();

    /**
     * Model tests for WebHookEvents
     */
    @Test
    public void testWebHookEvents() {
        // TODO: test WebHookEvents
    }

    /**
     * Test the property 'datasetCreation'
     */
    @Test
    public void datasetCreationTest() {
        // TODO: test datasetCreation
    }

    /**
     * Test the property 'datasetProcessing'
     */
    @Test
    public void datasetProcessingTest() {
        // TODO: test datasetProcessing
    }

    /**
     * Test the property 'datasetCompletion'
     */
    @Test
    public void datasetCompletionTest() {
        // TODO: test datasetCompletion
    }

    /**
     * Test the property 'datasetDeletion'
     */
    @Test
    public void datasetDeletionTest() {
        // TODO: test datasetDeletion
    }

    /**
     * Test the property 'modelCreation'
     */
    @Test
    public void modelCreationTest() {
        // TODO: test modelCreation
    }

    /**
     * Test the property 'modelProcessing'
     */
    @Test
    public void modelProcessingTest() {
        // TODO: test modelProcessing
    }

    /**
     * Test the property 'modelCompletion'
     */
    @Test
    public void modelCompletionTest() {
        // TODO: test modelCompletion
    }

    /**
     * Test the property 'modelDeletion'
     */
    @Test
    public void modelDeletionTest() {
        // TODO: test modelDeletion
    }

    /**
     * Test the property 'evaluationCreation'
     */
    @Test
    public void evaluationCreationTest() {
        // TODO: test evaluationCreation
    }

    /**
     * Test the property 'evaluationProcessing'
     */
    @Test
    public void evaluationProcessingTest() {
        // TODO: test evaluationProcessing
    }

    /**
     * Test the property 'evaluationCompletion'
     */
    @Test
    public void evaluationCompletionTest() {
        // TODO: test evaluationCompletion
    }

    /**
     * Test the property 'evaluationDeletion'
     */
    @Test
    public void evaluationDeletionTest() {
        // TODO: test evaluationDeletion
    }

    /**
     * Test the property 'transcriptionCreation'
     */
    @Test
    public void transcriptionCreationTest() {
        // TODO: test transcriptionCreation
    }

    /**
     * Test the property 'transcriptionProcessing'
     */
    @Test
    public void transcriptionProcessingTest() {
        // TODO: test transcriptionProcessing
    }

    /**
     * Test the property 'transcriptionCompletion'
     */
    @Test
    public void transcriptionCompletionTest() {
        // TODO: test transcriptionCompletion
    }

    /**
     * Test the property 'transcriptionDeletion'
     */
    @Test
    public void transcriptionDeletionTest() {
        // TODO: test transcriptionDeletion
    }

    /**
     * Test the property 'endpointCreation'
     */
    @Test
    public void endpointCreationTest() {
        // TODO: test endpointCreation
    }

    /**
     * Test the property 'endpointProcessing'
     */
    @Test
    public void endpointProcessingTest() {
        // TODO: test endpointProcessing
    }

    /**
     * Test the property 'endpointCompletion'
     */
    @Test
    public void endpointCompletionTest() {
        // TODO: test endpointCompletion
    }

    /**
     * Test the property 'endpointDeletion'
     */
    @Test
    public void endpointDeletionTest() {
        // TODO: test endpointDeletion
    }

    /**
     * Test the property 'ping'
     */
    @Test
    public void pingTest() {
        // TODO: test ping
    }

    /**
     * Test the property 'challenge'
     */
    @Test
    public void challengeTest() {
        // TODO: test challenge
    }

}
